export default {
  raw_text: 'lots of stuff',
  title: '',
  description: '',
  elements: [
    {
      id: '0829fffc-f3a4-4245-87f7-593fdbc00f7b',
      group_id: 0,
      element_type: 'text',
      element_params: {
        text: 'Request to Change Name Case Number: (the clerk fills this in) ',
        text_style: 'DYNNJN+Arial-ItalicMT 8.879999999999995',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '19dec194-59e1-4eca-813f-5a7412e204d2',
      group_id: 1,
      element_type: 'text',
      element_params: {
        text: '8/08 (For An Adult) ',
        text_style: 'JTUTCJ+ArialMT 9.360000000000014',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '6bcaf632-d858-45c1-b074-ca7c14ae5215',
      group_id: 2,
      element_type: 'text',
      element_params: {
        text: 'In the Probate Court of (county): County, Alabama ',
        text_style: 'JTUTCJ+ArialMT 9.840000000000032',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_address_county instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_address_county',
            placeholder: '',
            instructions:
              'Type name of Alabama county where Probate Court is located',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: '19e53032-e4a2-4b81-8659-3f5c0e99e763',
      group_id: 3,
      element_type: 'text',
      element_params: {
        text: 'Your current name: ',
        text_style: 'JTUTCJ+ArialMT 9.840000000000032',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_name_first instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_name_first',
            placeholder: '',
            instructions: 'Type your current first name',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_name_middle instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_name_middle',
            placeholder: '',
            instructions: 'Type your current middle name',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_name_last instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_name_last',
            placeholder: '',
            instructions: 'Type your current last name',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: '26c1bba7-cc41-4f12-89d3-0d9c23fe53f6',
      group_id: 4,
      element_type: 'text',
      element_params: {
        text: 'first middle last ',
        text_style: 'DYNNJN+Arial-ItalicMT 8.879999999999995',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '9aadc2d5-6fcd-4573-a60d-ceb3c80ab940',
      group_id: 5,
      element_type: 'text',
      element_params: {
        text: 'To ask the court to change your name, you must fill out this form, and: ',
        text_style: 'JTUTCJ+ArialMT 10.799999999999955',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '283a742f-3af3-4088-8ac9-2c87b0985358',
      group_id: 6,
      element_type: 'text',
      element_params: {
        text: '• Attach a certified copy of your birth certificate and a copy of your photo ID, and ',
        text_style: 'JTUTCJ+ArialMT 10.799999999999955',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: 'b0673ffa-cb93-42fd-ad92-dd1b522a5bc2',
      group_id: 7,
      element_type: 'text',
      element_params: {
        text: '• File your form and attachments in the same county where you live. ',
        text_style: 'JTUTCJ+ArialMT 10.799999999999955',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: 'e19fc9d3-0b03-4776-9823-142e616d0c54',
      group_id: 8,
      element_type: 'text',
      element_params: {
        text: 'I declare that the following information is true: ',
        text_style: 'JTUTCJ+ArialMT 10.32000000000005',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '311fda7b-90e6-43df-a581-6f284bb6f980',
      group_id: 9,
      element_type: 'text',
      element_params: {
        text: 'My current name is: ',
        text_style: 'JTUTCJ+ArialMT 10.799999999999955',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_name_first__2 instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_name_first__2',
            placeholder: '',
            instructions: 'Type your current first name',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_name_middle__2 instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_name_middle__2',
            placeholder: '',
            instructions: 'Type your current middle name',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_name_last__2 instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_name_last__2',
            placeholder: '',
            instructions: 'Type your current last name',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: 'c5b562a9-213a-4e82-b0da-d50779fe864a',
      group_id: 10,
      element_type: 'text',
      element_params: {
        text: 'first middle last ',
        text_style: 'DYNNJN+Arial-ItalicMT 8.879999999999995',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: 'e9470682-e25c-406c-a055-32123d393c5e',
      group_id: 11,
      element_type: 'text',
      element_params: {
        text: 'My address is: ',
        text_style: 'JTUTCJ+ArialMT 10.799999999999955',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_address_line_one instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_address_line_one',
            placeholder: '',
            instructions: 'Type your street address',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_address_city instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_address_city',
            placeholder: '',
            instructions: 'Type the name of your city',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_address_state instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_address_state',
            placeholder: '',
            instructions: 'Type the state where you live',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_address_zip instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_address_zip',
            placeholder: '',
            instructions: 'Type your zip code',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: '5cf01a14-e9d4-4dd3-8e43-74553f2e1601',
      group_id: 12,
      element_type: 'text',
      element_params: {
        text: 'street city state zip ',
        text_style: 'DYNNJN+Arial-ItalicMT 8.879999999999995',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '6a37d6e9-cf89-4a13-aeb4-4a83f245295a',
      group_id: 13,
      element_type: 'text',
      element_params: {
        text: 'My phone numbers are (home): ',
        text_style: 'DYNNJN+Arial-ItalicMT 9.360000000000014',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_phone instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_phone',
            placeholder: '',
            instructions: 'Type your home phone number including area code',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: '43828c3b-5f3a-40bb-aba1-3e96998e1d92',
      group_id: 13,
      element_type: 'text',
      element_params: {
        text: ' (work): ',
        text_style: 'DYNNJN+Arial-ItalicMT 8.879999999999995',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=work_phone instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'work_phone',
            placeholder: '',
            instructions: 'Type your work phone number including area code',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: '528a3263-cedc-4b5f-911d-96b6c1662fbe',
      group_id: 14,
      element_type: 'text',
      element_params: {
        text: 'My date of birth is (mm/dd/yyyy): ',
        text_style: 'JTUTCJ+ArialMT 8.879999999999995',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_birthdate instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_birthdate',
            placeholder: '',
            instructions: 'Type your date of birth as mm/dd/yyyy',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: 'f981d686-a99a-4048-8fc1-9fdc39e67e91',
      group_id: 15,
      element_type: 'text',
      element_params: {
        text: 'My name at birth was: ',
        text_style: 'JTUTCJ+ArialMT 10.800000000000011',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_previous_names1_first instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_previous_names1_first',
            placeholder: '',
            instructions: 'Type the first name you were given at birth',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_previous_names1_middle instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_previous_names1_middle',
            placeholder: '',
            instructions: 'Type the middle name you were given at birth',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=users1_previous_names1_last instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'users1_previous_names1_last',
            placeholder: '',
            instructions: 'Type the last name you were given at birth',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: '355d1e7d-a80a-4bf7-a310-9c577be20df0',
      group_id: 16,
      element_type: 'text',
      element_params: {
        text: 'first middle last ',
        text_style: 'DYNNJN+Arial-ItalicMT 8.879999999999995',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '00360d8a-1871-417f-9a68-4b1d3339aa6d',
      group_id: 17,
      element_type: 'text',
      element_params: {
        text: 'I am an adult (19 or older), of sound mind, and live in (name of Alabama county): ',
        text_style: 'PCNLPI+TimesNewRomanPS-ItalicMT 8.879999999999995',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=user1_address_county__2 instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'user1_address_county__2',
            placeholder: '',
            instructions: 'Type the name of the county where you live now',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: '4503d8e8-7220-4267-8020-c46ef48013f7',
      group_id: 18,
      element_type: 'radio_group',
      element_params: {
        text: 'The attached copy of my photo ID is my (check one): ',
        text_style: 'heading',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: 'Driver’s license, #',
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'driver_license_number',
            placeholder: '',
            instructions: "Type your driver's license number",
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: 'Non-driver’s photo, ID #:',
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'non_driver_id_number',
            placeholder: '',
            instructions:
              "Type the number from your photo ID (not driver's license)",
            required: false,
            options: [],
          },
        },
      ],
      parent: 'photo_id',
    },
    {
      id: '3abc43d0-6c14-45ad-a5c1-1f2ec17776f7',
      group_id: 19,
      element_type: 'text',
      element_params: {
        text: 'I ask the court to change my name because (explain why you want to change your name): ',
        text_style: 'LEDWHU+TimesNewRomanPSMT 12.0',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '77938854-7d8f-4b80-bdf6-c3c10bb0b95d',
      group_id: 20,
      element_type: 'text',
      element_params: { text: '', text_style: '', options: [] },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=reasons_for_change instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'reasons_for_change',
            placeholder: '',
            instructions: 'Continue typing why you want to change your name',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: 'ee8f3a2b-0e0a-4ca9-9f4a-28ea57461a58',
      group_id: 21,
      element_type: 'text',
      element_params: {
        text: 'I want my new name to be: ',
        text_style: 'JTUTCJ+ArialMT 10.319999999999993',
        options: [],
      },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=user1_preferred_name_first instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'user1_preferred_name_first',
            placeholder: '',
            instructions: 'Type what you want your new first name to be',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=user1_preferred_name_middle instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'user1_preferred_name_middle',
            placeholder: '',
            instructions: 'Type what you want your new middle name to be',
            required: false,
            options: [],
          },
        },
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=user1_preferred_name_last instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 10 Tf',
            output_id: 'user1_preferred_name_last',
            placeholder: '',
            instructions: 'Type what you want your new last name to be',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: '1fa81ac6-2e8c-4714-a38d-7ac3813c2212',
      group_id: 22,
      element_type: 'text',
      element_params: {
        text: 'first middle last ',
        text_style: 'DYNNJN+Arial-ItalicMT 8.879999999999995',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '5b6c154f-4532-4564-a59c-5c4c41f0e009',
      group_id: 23,
      element_type: 'text',
      element_params: {
        text: 'I also declare: ',
        text_style: 'JTUTCJ+ArialMT 10.319999999999993',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '3d37cbc7-5a8a-4f4f-95fd-70177fcbff99',
      group_id: 24,
      element_type: 'text',
      element_params: {
        text: '• I am not now facing criminal charges, nor am I involved in any other court case. ',
        text_style: 'JTUTCJ+ArialMT 10.319999999999993',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: 'f0e53639-6e34-46f0-992e-65b6896d8df9',
      group_id: 25,
      element_type: 'text',
      element_params: {
        text: '• I have never been convicted of a criminal sex offense (as defined in Alabama Code § 15-20-21), ',
        text_style: 'JTUTCJ+ArialMT 10.319999999999993',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: 'db1b4660-879a-4c71-839f-b22e5a631c64',
      group_id: 26,
      element_type: 'text',
      element_params: {
        text: 'a crime of moral turpitude, or a felony. ',
        text_style: 'JTUTCJ+ArialMT 10.319999999999993',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: 'f25c5520-e734-4f2e-b478-6d76a444ca44',
      group_id: 27,
      element_type: 'text',
      element_params: {
        text: '• I am not asking to change my name to avoid paying my debts or to commit fraud. ',
        text_style: 'JTUTCJ+ArialMT 10.320000000000022',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '54db456c-36f5-42d8-b3ad-0d8f16e03600',
      group_id: 28,
      element_type: 'text',
      element_params: {
        text: '• I swear that all of the information I have provided above is complete and accurate. ',
        text_style: 'JTUTCJ+ArialMT 10.319999999999993',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '82495ae2-40c7-4a47-9397-8ea5a4b34db4',
      group_id: 29,
      element_type: 'text',
      element_params: {
        text: 'I ask the court to grant this request and to issue an order changing my name. ',
        text_style: 'JTUTCJ+ArialMT 10.319999999999993',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '26b1bb54-d25b-4592-a1d4-c4fffff4e9d7',
      group_id: 30,
      element_type: 'text',
      element_params: {
        text: 'Sign below in front of a notary: ',
        text_style: 'DYNNJN+Arial-ItalicMT 9.359999999999985',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '7f2ef1a8-b255-45b0-ac5f-dfe9296dc3cd',
      group_id: 31,
      element_type: 'text',
      element_params: { text: '', text_style: '', options: [] },
      inputs: [
        {
          input_type: 'Tx',
          input_params: {
            text: "<input label=signature_date instructions={field_dict['field_instructions']}>",
            text_style: '0 g\nHelvetica 12 Tf',
            output_id: 'signature_date',
            placeholder: '',
            instructions: '',
            required: false,
            options: [],
          },
        },
      ],
      parent: null,
    },
    {
      id: 'c96bc108-dab1-4e94-a801-670ae41530bf',
      group_id: 32,
      element_type: 'text',
      element_params: {
        text: ' Date: ',
        text_style: 'DYNNJN+Arial-ItalicMT 9.359999999999985',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '8f426a9a-3d34-45c3-989b-175074f6ad85',
      group_id: 33,
      element_type: 'text',
      element_params: {
        text: 'Notary fills out below— ',
        text_style: 'PEUTYI+Arial-BoldItalicMT 9.840000000000003',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: 'ea5b0bdd-f327-4fb5-bc5a-b7dd50193888',
      group_id: 34,
      element_type: 'text',
      element_params: {
        text: 'Sworn to and subscribed before me, the undersigned authority, ',
        text_style: 'LEDWHU+TimesNewRomanPSMT 7.920000000000002',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '3de1c76a-6133-4045-85b3-69070451a169',
      group_id: 35,
      element_type: 'text',
      element_params: {
        text: 'By (Print name of notary): ',
        text_style: 'LEDWHU+TimesNewRomanPSMT 7.920000000000002',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '9c553a4b-8d5b-4d10-9adb-7dbb59bb25a0',
      group_id: 36,
      element_type: 'text',
      element_params: {
        text: 'On this date: (Notary’s seal here) ',
        text_style: 'DYNNJN+Arial-ItalicMT 7.920000000000002',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '6c4854db-c41e-4c9b-a81b-7ede35be481e',
      group_id: 37,
      element_type: 'text',
      element_params: {
        text: ' / / ',
        text_style: 'JTUTCJ+ArialMT 10.799999999999997',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: '09795c53-ac7e-4f68-909f-ea6ac44148f2',
      group_id: 38,
      element_type: 'text',
      element_params: {
        text: ' Notary signs here Date notary’s commission expires ',
        text_style: 'PCNLPI+TimesNewRomanPS-ItalicMT 7.920000000000002',
        options: [],
      },
      inputs: [],
      parent: null,
    },
    {
      id: 'f5eb84e9-20e6-45c8-a6ac-5a116781b032',
      group_id: 39,
      element_type: 'text',
      element_params: {
        text: 'Rev. 8/08 \uf8e9 2008 Alabama State Bar ',
        text_style: 'JTUTCJ+ArialMT 8.880000000000003',
        options: [],
      },
      inputs: [],
      parent: null,
    },
  ],
  raw_fields: [
    {
      type: '/Tx',
      var_name: 'users1_address_line_one',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [148.8, 528.48, 284.625, 542.64],
        field_label: 'users1_address_line_one',
        field_instructions: 'Type your street address',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_address_city',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [286.978, 527.52, 391.19, 542.426],
        field_label: 'users1_address_city',
        field_instructions: 'Type the name of your city',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_address_state',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [392.74, 528.165, 462.129, 542.426],
        field_label: 'users1_address_state',
        field_instructions: 'Type the state where you live',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_address_zip',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [464.324, 527.52, 554.993, 543.071],
        field_label: 'users1_address_zip',
        field_instructions: 'Type your zip code',
      },
    },
    {
      type: '/Tx',
      var_name: 'work_phone',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [392.88, 500.16, 555.48, 514.32],
        field_label: 'work_phone',
        field_instructions: 'Type your work phone number including area code',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_birthdate',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [224.16, 480.48, 555.48, 494.64],
        field_label: 'users1_birthdate',
        field_instructions: 'Type your date of birth as mm/dd/yyyy',
      },
    },
    {
      type: '/Btn',
      var_name: 'photo_id',
      field_dict: {
        font_info: '/ZaDb 10 Tf 0 g',
        flags: 49152,
        field_type: 'button_field',
        field_label: 'photo_id',
        child_fields: [
          {
            coordinates: [321.512, 405.766, 331.773, 416.027],
          },
          {
            coordinates: [319.867, 391.578, 330.773, 403.129],
          },
        ],
        num_children: 2,
        field_instructions: '',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_phone',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [224.4, 500.16, 359.16, 514.32],
        field_label: 'users1_phone',
        field_instructions: 'Type your home phone number including area code',
      },
    },
    {
      type: '/Tx',
      var_name: 'reasons_for_change',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 4096,
        field_type: 'text_field',
        coordinates: [77.52, 347.096, 555.48, 374.64],
        field_label: 'reasons_for_change',
        field_instructions: 'Continue typing why you want to change your name',
      },
    },
    {
      type: '/Tx',
      var_name: 'non_driver_id_number',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [436.08, 393.6, 555.48, 405.885],
        field_label: 'non_driver_id_number',
        field_instructions:
          "Type the number from your photo ID (not driver's license)",
      },
    },
    {
      type: '/Tx',
      var_name: 'driver_license_number',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [410.64, 406.08, 555.48, 420.24],
        field_label: 'driver_license_number',
        field_instructions: "Type your driver's license number",
      },
    },
    {
      type: '/Tx',
      var_name: 'user1_preferred_name_first',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [207.84, 326.4, 333.637, 340.56],
        field_label: 'user1_preferred_name_first',
        field_instructions: 'Type what you want your new first name to be',
      },
    },
    {
      type: '/Tx',
      var_name: 'user1_preferred_name_middle',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [335.989, 326.313, 449.876, 340.575],
        field_label: 'user1_preferred_name_middle',
        field_instructions: 'Type what you want your new middle name to be',
      },
    },
    {
      type: '/Tx',
      var_name: 'user1_preferred_name_last',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [450.781, 325.668, 564.021, 340.575],
        field_label: 'user1_preferred_name_last',
        field_instructions: 'Type what you want your new last name to be',
      },
    },
    {
      type: '/Tx',
      var_name: 'signature_date',
      field_dict: {
        font_info: '0 g\n/Helvetica 12 Tf',
        field_type: 'text_field',
        coordinates: [391.163, 167.134, 541.163, 189.134],
        field_label: 'signature_date',
        field_instructions: '',
      },
    },
    {
      type: '/Tx',
      var_name: 'user1_address_county__2',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [434.16, 428.64, 555.48, 442.8],
        field_label: 'user1_address_county__2',
        field_instructions: 'Type the name of the county where you live now',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_previous_names1_middle',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [324.381, 457.872, 445.361, 472.133],
        field_label: 'users1_previous_names1_middle',
        field_instructions: 'Type the middle name you were given at birth',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_previous_names1_first',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [182.64, 457.68, 320.739, 471.84],
        field_label: 'users1_previous_names1_first',
        field_instructions: 'Type the first name you were given at birth',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_previous_names1_last',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [446.911, 457.872, 554.993, 472.133],
        field_label: 'users1_previous_names1_last',
        field_instructions: 'Type the last name you were given at birth',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_name_first__2',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [175.92, 557.04, 330.412, 571.2],
        field_label: 'users1_name_first__2',
        field_instructions: 'Type your current first name',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_name_middle__2',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [335.345, 557.185, 456.324, 572.091],
        field_label: 'users1_name_middle__2',
        field_instructions: 'Type your current middle name',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_name_last__2',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [459.809, 557.185, 555.638, 572.091],
        field_label: 'users1_name_last__2',
        field_instructions: 'Type your current last name',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_name_middle',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [319.867, 660.368, 446.006, 674.629],
        field_label: 'users1_name_middle',
        field_instructions: 'Type your current middle name',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_name_last',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [448.846, 661.013, 552.413, 674.629],
        field_label: 'users1_name_last',
        field_instructions: 'Type your current last name',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_name_first',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [143.52, 660.72, 315.114, 674.88],
        field_label: 'users1_name_first',
        field_instructions: 'Type your current first name',
      },
    },
    {
      type: '/Tx',
      var_name: 'users1_address_county',
      field_dict: {
        font_info: '0 g\n/Helvetica 10 Tf',
        flags: 0,
        field_type: 'text_field',
        coordinates: [221.76, 685.275, 413.28, 700.08],
        field_label: 'users1_address_county',
        field_instructions:
          'Type name of Alabama county where Probate Court is located',
      },
    },
  ],
};
