export const mockResponse = {
  message: 'PDF parsed successfully',
  parsed_pdf: {
    raw_text:
      "OMB Control No: 1123-0014 Expires 03/31/2027 \nAPPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF \nSIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF \nMARIJUANA \nOn October 6, 2022, President Biden issued a presidential proclamation that pardoned many federal and D.C. \noffenses for simple marijuana possession. On December 22, 2023, President Biden issued another proclamation that \nexpanded the relief provided by the original proclamation by pardoning the federal offenses of simple possession, \nattempted possession, and use of marijuana. \nHow a pardon can help you \nA pardon is an expression of the President’s forgiveness. It does not mean you are innocent or expunge your \nconviction. But it does remove civil disabilities—such as restrictions on the right to vote, to hold office, or to sit \non a jury—that are imposed because of the pardoned conviction. It may also be helpful in obtaining licenses, \nbonding, or employment. Learn more about the pardon. \nYou qualify for the pardon if: \n• On or before December 22, 2023, you were charged with or convicted of simple possession, attempted \npossession, or use of marijuana under the federal code, the District of Columbia code, or the Code of \nFederal Regulations \n• You were a U.S. citizen or lawfully present in the United States at the time of the offense \n• You were a U.S. citizen or lawful permanent resident on December 22, 2023 \nRequest a certificate to show proof of the pardon \nA Certificate of Pardon is proof that you were pardoned under the proclamation. The certificate is the only \ndocumentation you will receive of the pardon. Use the application below to start your request. \nWhat you'll need for the request \nAbout you \nYou can submit a request for yourself or someone else can submit on your behalf. You must provide \npersonal details, like name or citizenship status and either a mailing address, an email address or both to \ncontact you. We strongly recommend including an email address, if available, as we may not be able to \nrespond as quickly if you do not provide it. You can also use the mailing address or email address of \nanother person, if you do not have your own. \nAbout the charge or conviction \nYou must state whether it was a charge or conviction, the court district where it happened, and the date \n(month, day, year). If possible, you should also: \n• enter information about your case (docket or case number and the code section that was \ncharged) \n• upload your documents \no charging documents, like the indictment, complaint, criminal information, ticket or \ncitation; or \no conviction documents, like the judgment of conviction, the court docket sheet showing \nthe sentence and date it was imposed, or if you did not go to court, the receipt showing \npayment of fine \nIf you were charged by a ticket or citation and paid a fine instead of appearing in court, you should also provide the \ndate of conviction or the date the fine was paid. \nWithout this information, we can't guarantee that we'll be able to determine if you qualify for the pardon under \nthe proclamation. \n \nPage 1 of 4 \nUnited States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024 OMB Control No: 1123-0014 Expires 03/31/2027 \nAPPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF \nSIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF \nMARIJUANA \nInstructions: \nAn online version of this application is available at: Presidential Proclamation on Marijuana Possession \n(justice.gov). You can also complete and return this application with the required documents to \nUSPardon.Attorney@usdoj.gov or U.S. Department of Justice, Office of the Pardon Attorney, 950 Pennsylvania \nAvenue NW, Washington, DC 20530. \nPublic Burden Statement: \nThis collection meets the requirements of 44 U.S.C. § 3507, as amended by the Paperwork Reduction Act of 1995. \nWe estimate that it will take 120 minutes to read the instructions, gather the relevant materials, and answer \nquestions on the form. Send comments regarding the burden estimate or any other aspect of this collection of \ninformation, including suggestions for reducing this burden, to Office of the Pardon Attorney, U.S. Department of \nJustice, Attn: OMB Number 1123-0014, RFK Building, 950 Pennsylvania Avenue, N.W., Washington DC 20530. \nThe OMB Clearance number, 1123-0014, is currently valid. \nPrivacy Act Statement: \nThe Office of the Pardon Attorney has authority to collect this information under the U.S. Constitution, Article \nII, Section 2 (the pardon clause); Orders of the Attorney General Nos. 1798-93, 58 Fed. Reg. 53658 and 53659 \n(1993), 2317-2000, 65 Fed. Reg. 48381 (2000), and 2323-2000, 65 Fed. Reg. 58223 and 58224 (2000), codified in \n28 C.F.R. §§ 1.1 et seq. (the rules governing petitions for executive clemency); and Order of the Attorney General \nNo. 1012-83, 48 Fed. Reg. 22290 (1983), as codified in 28 C.F.R. §§ 0.35 and 0.36 (the authority of the Office of \nthe Pardon Attorney). The principal purpose for collecting this information is to enable the Office of the Pardon \nAttorney to issue an individual certificate of pardon to you. The routine uses which may be made of this \ninformation include provision of data to the President and his staff, other governmental entities, and the public. \nThe full list of routine uses for this correspondence can be found in the System of Records Notice titled, “Privacy \nAct of 1974; System of Records,” published in Federal Register, September 15, 2011, Vol. 76, No. 179, at pages \n57078 through 57080; as amended by “Privacy Act of 1974; System of Records,” published in the Federal \nRegister, May 25, 2017, Vol. 82, No. 100, at page 24161, and at the U.S. Department of Justice, Office of Privacy \nand Civil Liberties' website at: https://www.justice.gov/opcl/doj-systems-records#OPA. \nBy signing the attached form, you consent to allowing the Office of the Pardon Attorney to obtain information \nregarding your citizenship and/or immigration status from the courts, from other government agencies, from other \ncomponents within the Department of Justice, and from the Department of Homeland Security, U.S. Citizenship \nand Immigration Services (DHS-USCIS), Systematic Alien Verification for Entitlements (SAVE) program. The \ninformation received from these sources will be used for the sole purposes of determining an applicant's \nqualification for a Certificate of Pardon under the (cid:37)(cid:70)(cid:68)(cid:70)(cid:78)(cid:67)(cid:70)(cid:83)(cid:1)(cid:19)(cid:19) proclamation and for record-keeping of those \ndeterminations. Further, please be aware that if the Office of the Pardon Attorney is unable to verify your \ncitizenship or immigration status based on the information provided below, we may contact you to obtain \nadditional verification information. Learn more about the DHS-USCIS's SAVE program and its ordinary uses. \nYour disclosure of information to the Office of the Pardon Attorney on this form is voluntary. If you do not \ncomplete all or some of the information fields in this form, however, the Office of the Pardon Attorney may not be \nable to effectively respond. Information regarding gender, race, or ethnicity is not required and will not affect the \nprocessing of the application. \nNote: Submit a separate form for each conviction or charge for which you are seeking a certificate of pardon. \nApplication Form on page 3. \nPage 2 of 4 \nUnited States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024 OMB Control No: 1123-0014 Expires 03/31/2027 \nAPPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF \nSIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF \nMARIJUANA \nComplete the following: \nName: \n(first) (middle) (last) \nName at Conviction: \n(if different) (first) (middle) (last) \nAddress: \n(number) (street) (apartment/unit no.) \n\n(city) (state) (Zip Code) \nEmail Address:  Phone Number:  \nDate of Birth: Gender:  Are you Hispanic or Latino?: Yes No \nRace: Alaska Native or American Indian Asian Black or African American \nNative Hawaiian or Other Pacific Islander White Other \nCitizenship or Residency Status: \nU.S. citizen by birth \nU.S. naturalized citizen Date Naturalization Granted: \nLawful Permanent Resident Date Residency Granted: \nAlien Registration Number (A-Number), Certificate of Naturalization Number, or Citizenship Number \n(if applicant is a lawful permanent resident or naturalized citizen):  \n(A-Number) \n1.  Applicant was convicted on:  (month/day/year) in the U.S. District Court for the  (Northern, etc.) \nDistrict of  (state) or D.C. Superior Court of simple possession of marijuana, under \nDocket No. : (docket number) and Code Section:  ; (code section) OR \n2.  Applicant was charged with Code Section: (code section)  in the U.S. District Court for the  (Eastern, etc.) \nDistrict of  (state) or D.C. Superior Court under Docket No:  (docket number) \n \nUnited States Department of Justice Office of the Pardon Attorney Page 3 of 4 Washington, D.C. 20530 January 2024 OMB Control No: 1123-0014 Expires 03/31/2027 \nAPPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF \nSIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF \nMARIJUANA \nWith knowledge of the penalties for false statements to Federal Agencies, as provided by 18 \nU.S.C. § 1001, and with knowledge that this statement is submitted by me to affect action by \nthe U.S. Department of Justice, I certify that: \n1. The applicant was either a U.S. citizen or lawfully present in the United States at the time of the \noffense. \n2. The applicant was a U.S. citizen or lawful permanent resident on December 22, 2023. \n3. The above statements, and accompanying documents, are true and complete to the \n best of my knowledge, information, and belief. \n4. I acknowledge that any certificate issued in reliance on the above information will be \nvoided, if the information is subsequently determined to be false. \n\n(date) (signature) \nPage 4 of 4 \nUnited States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024 ",
    form_summary: {
      component_type: 'form_summary',
      title: 'My Form Title',
      description: 'My Form Description',
    },
    elements: [
      {
        component_type: 'paragraph',
        text: 'OMB Control No: 1123-0014 Expires 03/31/2027',
        line_id: 0,
        item_id: '0_1',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999964',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'APPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF SIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF MARIJUANA',
        line_id: 3,
        item_id: '3_0',
        font_info: 'AAAAAH+TimesNewRomanPS-BoldMT 14.039999999999964',
        page: 1,
        font_size: 14,
        font_modifiers: ['bold'],
        font_tag: 'h2',
      },
      {
        component_type: 'paragraph',
        text: 'On October 6, 2022, President Biden issued a presidential proclamation that pardoned many federal and D.C. offenses for simple marijuana possession. On December 22, 2023, President Biden issued another proclamation that expanded the relief provided by the original proclamation by pardoning the federal offenses of simple possession, attempted possession, and use of marijuana.',
        line_id: 7,
        item_id: '7_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999964',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'How a pardon can help you',
        line_id: 8,
        item_id: '8_0',
        font_info: 'AAAAAH+TimesNewRomanPS-BoldMT 12.0',
        page: 1,
        font_size: 12,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'A pardon is an expression of the President’s forgiveness. It does not mean you are innocent or expunge your conviction. But it does remove civil disabilities—such as restrictions on the right to vote, to hold office, or to sit on a jury—that are imposed because of the pardoned conviction. It may also be helpful in obtaining licenses, bonding, or employment. Learn more about the pardon.',
        line_id: 12,
        item_id: '12_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999964',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'You qualify for the pardon if:',
        line_id: 13,
        item_id: '13_0',
        font_info: 'AAAAAH+TimesNewRomanPS-BoldMT 12.0',
        page: 1,
        font_size: 12,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: '• On or before December 22, 2023, you were charged with or convicted of simple possession, attempted possession, or use of marijuana under the federal code, the District of Columbia code, or the Code of Federal Regulations • You were a U.S. citizen or lawfully present in the United States at the time of the offense • You were a U.S. citizen or lawful permanent resident on December 22, 2023',
        line_id: 18,
        item_id: '18_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999964',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'Request a certificate to show proof of the pardon',
        line_id: 19,
        item_id: '19_0',
        font_info: 'AAAAAH+TimesNewRomanPS-BoldMT 12.0',
        page: 1,
        font_size: 12,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'A Certificate of Pardon is proof that you were pardoned under the proclamation. The certificate is the only documentation you will receive of the pardon. Use the application below to start your request.',
        line_id: 21,
        item_id: '21_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999964',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: "What you'll need for the request",
        line_id: 22,
        item_id: '22_0',
        font_info: 'AAAAAH+TimesNewRomanPS-BoldMT 12.0',
        page: 1,
        font_size: 12,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'About you',
        line_id: 23,
        item_id: '23_0',
        font_info: 'AAAAAH+TimesNewRomanPS-BoldMT 11.039999999999964',
        page: 1,
        font_size: 11,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'You can submit a request for yourself or someone else can submit on your behalf. You must provide personal details, like name or citizenship status and either a mailing address, an email address or both to contact you. We strongly recommend including an email address, if available, as we may not be able to respond as quickly if you do not provide it. You can also use the mailing address or email address of another person, if you do not have your own.',
        line_id: 28,
        item_id: '28_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999964',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'About the charge or conviction',
        line_id: 29,
        item_id: '29_0',
        font_info: 'AAAAAH+TimesNewRomanPS-BoldMT 11.039999999999964',
        page: 1,
        font_size: 11,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'You must state whether it was a charge or conviction, the court district where it happened, and the date (month, day, year). If possible, you should also:',
        line_id: 31,
        item_id: '31_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999992',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: '•',
        line_id: 33,
        item_id: '33_0',
        font_info: 'AAAAAI+SymbolMT 11.039999999999992',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'enter information about your case (docket or case number and the code section that was charged)',
        line_id: 34,
        item_id: '34_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999992',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: '•',
        line_id: 36,
        item_id: '36_0',
        font_info: 'AAAAAI+SymbolMT 11.039999999999992',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'upload your documents o charging documents, like the indictment, complaint, criminal information, ticket or',
        line_id: 37,
        item_id: '37_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999992',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'citation; or',
        line_id: 38,
        item_id: '38_0',
        font_info: 'AAAAAH+TimesNewRomanPS-BoldMT 11.039999999999992',
        page: 1,
        font_size: 11,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'o conviction documents, like the judgment of conviction, the court docket sheet showing the sentence and date it was imposed, or if you did not go to court, the receipt showing',
        line_id: 40,
        item_id: '40_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999992',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'payment of fine If you were charged by a ticket or citation and paid a fine instead of appearing in court, you should also provide the date of conviction or the date the fine was paid.',
        line_id: 43,
        item_id: '43_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.040000000000006',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: "Without this information, we can't guarantee that we'll be able to determine if you qualify for the pardon under",
        line_id: 44,
        item_id: '44_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.039999999999992',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'the proclamation.',
        line_id: 45,
        item_id: '45_0',
        font_info: 'AAAAAD+TimesNewRomanPSMT 11.04',
        page: 1,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'Page 1 of 4',
        line_id: 47,
        item_id: '47_0',
        font_info: 'AAAAAF+TimesNewRomanPS-BoldItalicMT 9.0',
        page: 1,
        font_size: 9,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'United States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024',
        line_id: 48,
        item_id: '48_2',
        font_info: 'AAAAAF+TimesNewRomanPS-BoldItalicMT 8.04',
        page: 1,
        font_size: 8,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'OMB Control No: 1123-0014 Expires 03/31/2027',
        line_id: 0,
        item_id: '0_2',
        font_info: 'AAAAAM+TimesNewRomanPSMT 11.039999999999964',
        page: 2,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'APPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF SIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF MARIJUANA Instructions:',
        line_id: 4,
        item_id: '4_0',
        font_info: 'AAAAAO+TimesNewRomanPS-BoldMT 14.039999999999964',
        page: 2,
        font_size: 14,
        font_modifiers: ['bold'],
        font_tag: 'h2',
      },
      {
        component_type: 'paragraph',
        text: 'An online version of this application is available at: Presidential Proclamation on Marijuana Possession (justice.gov). You can also complete and return this application with the required documents to USPardon.Attorney@usdoj.gov or U.S. Department of Justice, Office of the Pardon Attorney, 950 Pennsylvania Avenue NW, Washington, DC 20530.',
        line_id: 8,
        item_id: '8_0',
        font_info: 'AAAAAM+TimesNewRomanPSMT 11.039999999999964',
        page: 2,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'Public Burden Statement:',
        line_id: 9,
        item_id: '9_0',
        font_info: 'AAAAAO+TimesNewRomanPS-BoldMT 14.039999999999964',
        page: 2,
        font_size: 14,
        font_modifiers: ['bold'],
        font_tag: 'h2',
      },
      {
        component_type: 'paragraph',
        text: 'This collection meets the requirements of 44 U.S.C. § 3507, as amended by the Paperwork Reduction Act of 1995. We estimate that it will take 120 minutes to read the instructions, gather the relevant materials, and answer questions on the form. Send comments regarding the burden estimate or any other aspect of this collection of information, including suggestions for reducing this burden, to Office of the Pardon Attorney, U.S. Department of',
        line_id: 13,
        item_id: '13_0',
        font_info: 'AAAAAM+TimesNewRomanPSMT 11.039999999999964',
        page: 2,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'Justice, Attn: OMB Number 1123-0014, RFK Building, 950 Pennsylvania Avenue, N.W., Washington DC 20530.',
        line_id: 14,
        item_id: '14_0',
        font_info: 'AAAAAM+TimesNewRomanPSMT 11.04000000000002',
        page: 2,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'The OMB Clearance number, 1123-0014, is currently valid.',
        line_id: 15,
        item_id: '15_0',
        font_info: 'AAAAAM+TimesNewRomanPSMT 11.039999999999964',
        page: 2,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'Privacy Act Statement:',
        line_id: 16,
        item_id: '16_0',
        font_info: 'AAAAAO+TimesNewRomanPS-BoldMT 14.04000000000002',
        page: 2,
        font_size: 14,
        font_modifiers: ['bold'],
        font_tag: 'h2',
      },
      {
        component_type: 'paragraph',
        text: "The Office of the Pardon Attorney has authority to collect this information under the U.S. Constitution, Article II, Section 2 (the pardon clause); Orders of the Attorney General Nos. 1798-93, 58 Fed. Reg. 53658 and 53659 (1993), 2317-2000, 65 Fed. Reg. 48381 (2000), and 2323-2000, 65 Fed. Reg. 58223 and 58224 (2000), codified in 28 C.F.R. §§ 1.1 et seq. (the rules governing petitions for executive clemency); and Order of the Attorney General No. 1012-83, 48 Fed. Reg. 22290 (1983), as codified in 28 C.F.R. §§ 0.35 and 0.36 (the authority of the Office of the Pardon Attorney). The principal purpose for collecting this information is to enable the Office of the Pardon Attorney to issue an individual certificate of pardon to you. The routine uses which may be made of this information include provision of data to the President and his staff, other governmental entities, and the public. The full list of routine uses for this correspondence can be found in the System of Records Notice titled, “Privacy Act of 1974; System of Records,” published in Federal Register, September 15, 2011, Vol. 76, No. 179, at pages 57078 through 57080; as amended by “Privacy Act of 1974; System of Records,” published in the Federal Register, May 25, 2017, Vol. 82, No. 100, at page 24161, and at the U.S. Department of Justice, Office of Privacy and Civil Liberties' website at: https://www.justice.gov/opcl/doj-systems-records#OPA. By signing the attached form, you consent to allowing the Office of the Pardon Attorney to obtain information regarding your citizenship and/or immigration status from the courts, from other government agencies, from other components within the Department of Justice, and from the Department of Homeland Security, U.S. Citizenship",
        line_id: 32,
        item_id: '32_0',
        font_info: 'AAAAAM+TimesNewRomanPSMT 11.039999999999964',
        page: 2,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: "and Immigration Services (DHS-USCIS), Systematic Alien Verification for Entitlements (SAVE) program. The information received from these sources will be used for the sole purposes of determining an applicant's qualification for a Certificate of Pardon under the (cid:37)(cid:70)(cid:68)(cid:70)(cid:78)(cid:67)(cid:70)(cid:83)(cid:1)(cid:19)(cid:19) proclamation and for record-keeping of those determinations. Further, please be aware that if the Office of the Pardon Attorney is unable to verify your citizenship or immigration status based on the information provided below, we may contact you to obtain additional verification information. Learn more about the DHS-USCIS's SAVE program and its ordinary uses. Your disclosure of information to the Office of the Pardon Attorney on this form is voluntary. If you do not complete all or some of the information fields in this form, however, the Office of the Pardon Attorney may not be",
        line_id: 40,
        item_id: '40_0',
        font_info: 'AAAAAM+TimesNewRomanPSMT 11.039999999999992',
        page: 2,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'able to effectively respond. Information regarding gender, race, or ethnicity is not required and will not affect the processing of the application.',
        line_id: 42,
        item_id: '42_0',
        font_info: 'AAAAAM+TimesNewRomanPSMT 11.040000000000006',
        page: 2,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'Note: Submit a separate form for each conviction or charge for which you are seeking a certificate of pardon.',
        line_id: 43,
        item_id: '43_0',
        font_info: 'AAAAAO+TimesNewRomanPS-BoldMT 11.040000000000006',
        page: 2,
        font_size: 11,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'Application Form on page 3.',
        line_id: 44,
        item_id: '44_0',
        font_info: 'AAAAAO+TimesNewRomanPS-BoldMT 11.999999999999993',
        page: 2,
        font_size: 12,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'Page 2 of 4',
        line_id: 45,
        item_id: '45_0',
        font_info: 'AAAAAQ+TimesNewRomanPS-BoldItalicMT 9.0',
        page: 2,
        font_size: 9,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'United States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024',
        line_id: 46,
        item_id: '46_2',
        font_info: 'AAAAAQ+TimesNewRomanPS-BoldItalicMT 8.04',
        page: 2,
        font_size: 8,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'OMB Control No: 1123-0014 Expires 03/31/2027',
        line_id: 0,
        item_id: '0_2',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999964',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'APPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF SIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF MARIJUANA',
        line_id: 3,
        item_id: '3_0',
        font_info: 'AAAAAT+TimesNewRomanPS-BoldMT 14.039999999999964',
        page: 3,
        font_size: 14,
        font_modifiers: ['bold'],
        font_tag: 'h2',
      },
      {
        component_type: 'paragraph',
        text: 'Complete the following:',
        line_id: 4,
        item_id: '4_0',
        font_info: 'AAAAAT+TimesNewRomanPS-BoldMT 12.0',
        page: 3,
        font_size: 12,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend: 'Name: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Fst Name 1',
            label: 'First Name',
            default_value: '',
            required: true,
          },
          {
            component_type: 'text_input',
            id: 'Mid Name 1',
            label: 'Middle Name',
            default_value: '',
            required: true,
          },
          {
            component_type: 'text_input',
            id: 'Lst Name 1',
            label: 'Last Name',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(first) (middle) (last)',
        line_id: 9,
        item_id: '9_2',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 9.0',
        page: 3,
        font_size: 9,
        font_modifiers: ['small'],
      },
      {
        component_type: 'fieldset',
        legend: 'Name at Conviction: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Conv Fst Name',
            label: 'First Name at Conviction',
            default_value: '',
            required: true,
          },
          {
            component_type: 'text_input',
            id: 'Conv Mid Name',
            label: 'Middle Name at Conviction',
            default_value: '',
            required: true,
          },
          {
            component_type: 'text_input',
            id: 'Conv Lst Name',
            label: 'Last Name at Conviction',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(if different) (first) (middle) (last)',
        line_id: 14,
        item_id: '14_3',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 9.0',
        page: 3,
        font_size: 9,
        font_modifiers: ['small'],
      },
      {
        component_type: 'fieldset',
        legend: 'Address: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Address',
            label: 'Address (number, street, apartment/unit number)',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(number) (street) (apartment/unit no.)',
        line_id: 17,
        item_id: '17_2',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 9.0',
        page: 3,
        font_size: 9,
        font_modifiers: ['small'],
      },
      {
        component_type: 'fieldset',
        legend: 'City',
        fields: [
          {
            component_type: 'text_input',
            id: 'City',
            label: 'City',
            default_value: '',
            required: true,
          },
          {
            component_type: 'text_input',
            id: 'State',
            label: 'State',
            default_value: '',
            required: true,
          },
          {
            component_type: 'text_input',
            id: 'Zip Code',
            label: '(Zip Code)',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(city) (state) (Zip Code)',
        line_id: 19,
        item_id: '19_2',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 9.0',
        page: 3,
        font_size: 9,
        font_modifiers: ['small'],
      },
      {
        component_type: 'fieldset',
        legend: 'Email Address: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Email Address',
            label: 'Email Address',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'fieldset',
        legend: 'Phone Number: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Phone Number',
            label: 'Phone Number',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: 'Date of Birth: Gender:',
        line_id: 24,
        item_id: '24_0',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999964',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend: 'Date of Birth',
        fields: [
          {
            component_type: 'text_input',
            id: 'Date of Birth',
            label: 'Date of Birth',
            default_value: '',
            required: true,
          },
          {
            component_type: 'text_input',
            id: 'Gender',
            label: 'Gender',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: 'Yes',
        line_id: 24,
        item_id: '24_5',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999964',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'radio_group',
        legend: 'Are you Hispanic or Latino?: ',
        options: [
          {
            id: 'Ethnicity/Yes',
            label: 'Yes ',
            name: 'Ethnicity/Yes',
            default_checked: false,
          },
          {
            id: 'Ethnicity/No',
            label: 'No ',
            name: 'Ethnicity/No',
            default_checked: false,
          },
        ],
        id: 'Ethnicity',
        page: 3,
      },
      {
        component_type: 'fieldset',
        legend: 'Race:',
        fields: [
          {
            component_type: 'checkbox',
            id: 'Nat Amer',
            label: 'Alaska Native or American Indian ',
            default_checked: false,
            struct_parent: 20,
          },
          {
            component_type: 'checkbox',
            id: 'Asian',
            label: 'Asian ',
            default_checked: false,
            struct_parent: 21,
          },
          {
            component_type: 'checkbox',
            id: 'Blck Amer',
            label: 'Black or African American ',
            default_checked: false,
            struct_parent: 22,
          },
          {
            component_type: 'checkbox',
            id: 'Nat Haw Islander',
            label: 'Native Hawaiian or Other Pacific Islander ',
            default_checked: false,
            struct_parent: 23,
          },
          {
            component_type: 'checkbox',
            id: 'White',
            label: 'White ',
            default_checked: false,
            struct_parent: 24,
          },
          {
            component_type: 'checkbox',
            id: 'Other',
            label: 'Other ',
            default_checked: false,
            struct_parent: 25,
          },
        ],
        page: 3,
      },
      {
        component_type: 'radio_group',
        legend: 'Citizenship or Residency Status: ',
        options: [
          {
            id: 'Citizenship/Birth',
            label: 'U.S. citizen by birth ',
            name: 'Citizenship/Birth',
            default_checked: false,
          },
          {
            id: 'Citizenship/Naturalized',
            label: 'U.S. naturalized citizen ',
            name: 'Citizenship/Naturalized',
            default_checked: false,
          },
          {
            id: 'Citizenship/Permanent Resident',
            label: 'Lawful Permanent Resident ',
            name: 'Citizenship/Permanent Resident',
            default_checked: false,
          },
        ],
        id: 'Citizenship',
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: 'Date Naturalization Granted:',
        line_id: 34,
        item_id: '34_2',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999964',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend: 'Date Naturalization Granted: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Naturalization Date_af_date',
            label: 'date naturalization granted',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: 'Date Residency Granted:',
        line_id: 37,
        item_id: '37_2',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999964',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend: 'Date Residency Granted: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Residency Date_af_date',
            label: 'Date Residency Granted (mm/dd/yyyy)',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: 'Alien Registration Number (A-Number), Certificate of Naturalization Number, or Citizenship Number',
        line_id: 38,
        item_id: '38_0',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999964',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend:
          '(if applicant is a lawful permanent resident or naturalized citizen): ',
        fields: [
          {
            component_type: 'text_input',
            id: 'A-Number',
            label: 'Alien Registration, Naturalization, or Citizenship Number',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(A-Number)',
        line_id: 41,
        item_id: '41_0',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 8.039999999999992',
        page: 3,
        font_size: 8,
        font_modifiers: ['small'],
      },
      {
        component_type: 'paragraph',
        text: '1.',
        line_id: 45,
        item_id: '45_0',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999992',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend: ' Applicant was convicted on: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Convict-Date_af_date',
            label: 'Convict Date',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(month/day/year)',
        line_id: 45,
        item_id: '45_4',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 8.039999999999992',
        page: 3,
        font_size: 8,
        font_modifiers: ['small'],
      },
      {
        component_type: 'fieldset',
        legend: 'in the U.S. District Court for the ',
        fields: [
          {
            component_type: 'text_input',
            id: 'US District Court',
            label: 'US District Court',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(Northern, etc.)',
        line_id: 45,
        item_id: '45_8',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 8.039999999999992',
        page: 3,
        font_size: 8,
        font_modifiers: ['small'],
      },
      {
        component_type: 'fieldset',
        legend: 'District of ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Dist State',
            label: 'State',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'fieldset',
        legend: '(state)',
        fields: [
          {
            component_type: 'checkbox',
            id: 'D.C. Superior Court 2',
            label: 'or ',
            default_checked: false,
            struct_parent: 41,
          },
        ],
        page: 3,
      },
      {
        component_type: 'fieldset',
        legend: 'or',
        fields: [
          {
            component_type: 'checkbox',
            id: 'D.C. Superior Court 1',
            label: 'D.C. ',
            default_checked: false,
            struct_parent: 35,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: 'Superior Court of simple possession of marijuana, under :',
        line_id: 52,
        item_id: '52_1',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999992',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend: 'Docket No. ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Docket No',
            label: 'Docket Number',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(docket number)',
        line_id: 52,
        item_id: '52_3',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 8.039999999999992',
        page: 3,
        font_size: 8,
        font_modifiers: ['small'],
      },
      {
        component_type: 'paragraph',
        text: ';',
        line_id: 52,
        item_id: '52_5',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999992',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend: 'and Code Section: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Code Section',
            label: 'Code Section',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(code section)',
        line_id: 52,
        item_id: '52_7',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 8.039999999999992',
        page: 3,
        font_size: 8,
        font_modifiers: ['small'],
      },
      {
        component_type: 'paragraph',
        text: 'OR',
        line_id: 52,
        item_id: '52_8',
        font_info: 'AAAAAT+TimesNewRomanPS-BoldMT 11.039999999999992',
        page: 3,
        font_size: 11,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: '2.',
        line_id: 57,
        item_id: '57_0',
        font_info: 'AAAAAV+TimesNewRomanPSMT 11.039999999999992',
        page: 3,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: '(code section)',
        line_id: 57,
        item_id: '57_2',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 8.039999999999992',
        page: 3,
        font_size: 8,
        font_modifiers: ['small'],
      },
      {
        component_type: 'fieldset',
        legend: ' Applicant was charged with Code Section: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Code Section_2',
            label: 'Code Section',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'fieldset',
        legend: 'in the U.S. District Court for the ',
        fields: [
          {
            component_type: 'text_input',
            id: 'US District Court_2',
            label: 'U.S. District Court',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(Eastern, etc.)',
        line_id: 57,
        item_id: '57_8',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 8.039999999999992',
        page: 3,
        font_size: 8,
        font_modifiers: ['small'],
      },
      {
        component_type: 'fieldset',
        legend: 'District of ',
        fields: [
          {
            component_type: 'text_input',
            id: 'District 2',
            label: 'State',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'fieldset',
        legend: '(state)',
        fields: [
          {
            component_type: 'checkbox',
            id: 'D.C. Superior Court 2',
            label: 'or ',
            default_checked: false,
            struct_parent: 41,
          },
        ],
        page: 3,
      },
      {
        component_type: 'fieldset',
        legend: 'D.C. Superior Court under Docket No: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Docket No 2',
            label: 'Docket No 2',
            default_value: '',
            required: true,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(docket number)',
        line_id: 61,
        item_id: '61_9',
        font_info: 'AAAAAZ+TimesNewRomanPS-ItalicMT 8.039999999999992',
        page: 3,
        font_size: 8,
        font_modifiers: ['small'],
      },
      {
        component_type: 'paragraph',
        text: 'United States Department of Justice Office of the Pardon Attorney',
        line_id: 64,
        item_id: '64_1',
        font_info: 'AAAAAX+TimesNewRomanPS-BoldItalicMT 8.04',
        page: 3,
        font_size: 8,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'Page 3 of 4',
        line_id: 64,
        item_id: '64_2',
        font_info: 'AAAAAX+TimesNewRomanPS-BoldItalicMT 9.0',
        page: 3,
        font_size: 9,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'Washington, D.C. 20530 January 2024',
        line_id: 64,
        item_id: '64_3',
        font_info: 'AAAAAX+TimesNewRomanPS-BoldItalicMT 8.04',
        page: 3,
        font_size: 8,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'OMB Control No: 1123-0014 Expires 03/31/2027',
        line_id: 0,
        item_id: '0_2',
        font_info: 'AAAABB+TimesNewRomanPSMT 11.039999999999964',
        page: 4,
        font_size: 11,
        font_modifiers: [],
        font_tag: 'p',
      },
      {
        component_type: 'paragraph',
        text: 'APPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF SIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF MARIJUANA',
        line_id: 3,
        item_id: '3_0',
        font_info: 'AAAABF+TimesNewRomanPS-BoldMT 14.039999999999964',
        page: 4,
        font_size: 14,
        font_modifiers: ['bold'],
        font_tag: 'h2',
      },
      {
        component_type: 'paragraph',
        text: 'With knowledge of the penalties for false statements to Federal Agencies, as provided by 18 U.S.C. § 1001, and with knowledge that this statement is submitted by me to affect action by the U.S. Department of Justice, I certify that: 1. The applicant was either a U.S. citizen or lawfully present in the United States at the time of the offense. 2. The applicant was a U.S. citizen or lawful permanent resident on December 22, 2023. 3. The above statements, and accompanying documents, are true and complete to the best of my knowledge, information, and belief. 4. I acknowledge that any certificate issued in reliance on the above information will be voided, if the information is subsequently determined to be false.',
        line_id: 13,
        item_id: '13_0',
        font_info: 'AAAABD+TimesNewRomanPS-BoldItalicMT 12.0',
        page: 4,
        font_size: 12,
        font_modifiers: ['bold'],
        font_tag: 'p',
      },
      {
        component_type: 'fieldset',
        legend: 'App Date',
        fields: [
          {
            component_type: 'text_input',
            id: 'App Date',
            label: 'Date',
            default_value: '',
            required: true,
          },
        ],
        page: 4,
      },
      {
        component_type: 'paragraph',
        text: '(date) (signature)',
        line_id: 16,
        item_id: '16_1',
        font_info: 'AAAABD+TimesNewRomanPS-BoldItalicMT 9.960000000000036',
        page: 4,
        font_size: 10,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'Page 4 of 4',
        line_id: 17,
        item_id: '17_0',
        font_info: 'AAAABD+TimesNewRomanPS-BoldItalicMT 9.0',
        page: 4,
        font_size: 9,
        font_modifiers: ['bold', 'small'],
      },
      {
        component_type: 'paragraph',
        text: 'United States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024',
        line_id: 18,
        item_id: '18_2',
        font_info: 'AAAABD+TimesNewRomanPS-BoldItalicMT 8.04',
        page: 4,
        font_size: 8,
        font_modifiers: ['bold', 'small'],
      },
    ],
    raw_fields: [
      {
        type: '/Tx',
        var_name: 'Fst Name 1',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [97, 636.96, 233.28, 659.64],
          field_label: 'Fst Name 1',
          field_instructions: 'First Name',
          struct_parent: 4,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Fst Name 1',
        struct_parent: 4,
      },
      {
        type: '/Tx',
        var_name: 'Mid Name 1',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [233.087, 637.581, 390.215, 659.32],
          field_label: 'Mid Name 1',
          field_instructions: 'Middle Name',
          struct_parent: 5,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Mid Name 1',
        struct_parent: 5,
      },
      {
        type: '/Tx',
        var_name: 'Lst Name 1',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [390.996, 637.493, 548.124, 659.232],
          field_label: 'Lst Name 1',
          field_instructions: 'Last Name',
          struct_parent: 6,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Lst Name 1',
        struct_parent: 6,
      },
      {
        type: '/Tx',
        var_name: 'Conv Fst Name',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [153.74, 598.085, 283.246, 620.765],
          field_label: 'Conv Fst Name',
          field_instructions: 'First Name at Conviction',
          struct_parent: 7,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Conv Fst Name',
        struct_parent: 7,
      },
      {
        type: '/Tx',
        var_name: 'Conv Mid Name',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [282.498, 598.164, 410.809, 620.844],
          field_label: 'Conv Mid Name',
          field_instructions: 'Middle Name at Conviction',
          struct_parent: 8,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Conv Mid Name',
        struct_parent: 8,
      },
      {
        type: '/Tx',
        var_name: 'Conv Lst Name',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [410.212, 597.677, 536.132, 620.358],
          field_label: 'Conv Lst Name',
          field_instructions: 'Last Name at Conviction',
          struct_parent: 9,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Conv Lst Name',
        struct_parent: 9,
      },
      {
        type: '/Tx',
        var_name: 'Address',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [102.84, 563.88, 547.08, 586.56],
          field_label: 'Address',
          field_instructions: 'Address (number, street, apartment/unit number)',
          struct_parent: 10,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Address',
        struct_parent: 10,
      },
      {
        type: '/Tx',
        var_name: 'City',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [64.5005, 531, 269.52, 551.88],
          field_label: 'City',
          field_instructions: 'City',
          struct_parent: 11,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'City',
        struct_parent: 11,
      },
      {
        type: '/Tx',
        var_name: 'State',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [273.96, 531, 440.52, 551.88],
          field_label: 'State',
          field_instructions: 'State',
          struct_parent: 12,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'State',
        struct_parent: 12,
      },
      {
        type: '/Tx',
        var_name: 'Zip Code',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [444.96, 531, 552.72, 551.88],
          field_label: 'Zip Code',
          field_instructions: '(Zip Code)',
          struct_parent: 13,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Zip Code',
        struct_parent: 13,
      },
      {
        type: '/Tx',
        var_name: 'Email Address',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [131.864, 489.6, 290.744, 512.28],
          field_label: 'Email Address',
          field_instructions: 'Email Address',
          struct_parent: 14,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Email Address',
        struct_parent: 14,
      },
      {
        type: '/Tx',
        var_name: 'Phone Number',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [385.68, 489.6, 549.6, 512.28],
          field_label: 'Phone Number',
          field_instructions: 'Phone Number',
          struct_parent: 15,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Phone Number',
        struct_parent: 15,
      },
      {
        type: '/Tx',
        var_name: 'Date of Birth',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [126.48, 451.68, 197.88, 474.36],
          field_label: 'Date of Birth',
          field_instructions: 'Date of Birth',
          struct_parent: 16,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Date of Birth',
        struct_parent: 16,
      },
      {
        type: '/Tx',
        var_name: 'Gender',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [241.56, 451.68, 313.08, 474.36],
          field_label: 'Gender',
          field_instructions: 'Gender',
          struct_parent: 17,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Gender',
        struct_parent: 17,
      },
      {
        type: '/Btn',
        var_name: '',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {
            '15': 'NoToggleToOff: (Radio buttons only) If set, exactly one radio button must be selected at all times; clicking the currently selected button has no effect. If clear, clicking the selected button deselects it, leaving no button selected.',
            '16': 'Radio: If set, the field is a set of radio buttons; if clear, the field is a check box. This flag is meaningful only if the Pushbutton flag is clear.',
          },
          coordinates: [505.619, 450.866, 523.619, 468.866],
          field_instructions: 'Yes',
          struct_parent: 18,
          name: 'Yes',
          field_type: '/Btn',
          field_label: '',
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Ethnicity/Yes',
        struct_parent: 18,
      },
      {
        type: '/Btn',
        var_name: '',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {
            '15': 'NoToggleToOff: (Radio buttons only) If set, exactly one radio button must be selected at all times; clicking the currently selected button has no effect. If clear, clicking the selected button deselects it, leaving no button selected.',
            '16': 'Radio: If set, the field is a set of radio buttons; if clear, the field is a check box. This flag is meaningful only if the Pushbutton flag is clear.',
          },
          coordinates: [558.213, 450.866, 576.213, 468.866],
          field_instructions: 'Yes',
          struct_parent: 19,
          name: 'No',
          field_type: '/Btn',
          field_label: '',
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Ethnicity/No',
        struct_parent: 19,
      },
      {
        type: '/Btn',
        var_name: 'Nat Amer',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Btn',
          coordinates: [280.102, 426.163, 298.102, 444.163],
          field_label: 'Nat Amer',
          field_instructions: 'Alaska Native or American Indian',
          struct_parent: 20,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Nat Amer',
        struct_parent: 20,
      },
      {
        type: '/Btn',
        var_name: 'Asian',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Btn',
          coordinates: [366.564, 426.163, 384.564, 444.163],
          field_label: 'Asian',
          field_instructions: 'Asian',
          struct_parent: 21,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Asian',
        struct_parent: 21,
      },
      {
        type: '/Btn',
        var_name: 'Blck Amer',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Btn',
          coordinates: [531.517, 426.163, 549.517, 444.163],
          field_label: 'Blck Amer',
          field_instructions: 'Black or African American',
          struct_parent: 22,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Blck Amer',
        struct_parent: 22,
      },
      {
        type: '/Btn',
        var_name: 'Nat Haw Islander',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Btn',
          coordinates: [309.587, 401.061, 327.587, 419.061],
          field_label: 'Nat Haw Islander',
          field_instructions: 'Native Hawaiian or Other Pacific Islander',
          struct_parent: 23,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Nat Haw Islander',
        struct_parent: 23,
      },
      {
        type: '/Btn',
        var_name: 'White',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Btn',
          coordinates: [438.681, 401.061, 456.681, 419.061],
          field_label: 'White',
          field_instructions: 'White',
          struct_parent: 24,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'White',
        struct_parent: 24,
      },
      {
        type: '/Btn',
        var_name: 'Other',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Btn',
          coordinates: [508.806, 401.061, 526.806, 419.061],
          field_label: 'Other',
          field_instructions: 'Other',
          struct_parent: 25,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Other',
        struct_parent: 25,
      },
      {
        type: '/Btn',
        var_name: '',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {
            '15': 'NoToggleToOff: (Radio buttons only) If set, exactly one radio button must be selected at all times; clicking the currently selected button has no effect. If clear, clicking the selected button deselects it, leaving no button selected.',
            '16': 'Radio: If set, the field is a set of radio buttons; if clear, the field is a check box. This flag is meaningful only if the Pushbutton flag is clear.',
          },
          coordinates: [98.4144, 349.663, 116.414, 367.663],
          field_instructions: 'U S Citizen by birth',
          struct_parent: 26,
          name: 'Birth',
          field_type: '/Btn',
          field_label: '',
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Citizenship/Birth',
        struct_parent: 26,
      },
      {
        type: '/Btn',
        var_name: '',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {
            '15': 'NoToggleToOff: (Radio buttons only) If set, exactly one radio button must be selected at all times; clicking the currently selected button has no effect. If clear, clicking the selected button deselects it, leaving no button selected.',
            '16': 'Radio: If set, the field is a set of radio buttons; if clear, the field is a check box. This flag is meaningful only if the Pushbutton flag is clear.',
          },
          coordinates: [98.4144, 331.733, 116.414, 349.733],
          field_instructions: 'U S naturalized citizen',
          struct_parent: 27,
          name: 'Naturalized',
          field_type: '/Btn',
          field_label: '',
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Citizenship/Naturalized',
        struct_parent: 27,
      },
      {
        type: '/Btn',
        var_name: '',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {
            '15': 'NoToggleToOff: (Radio buttons only) If set, exactly one radio button must be selected at all times; clicking the currently selected button has no effect. If clear, clicking the selected button deselects it, leaving no button selected.',
            '16': 'Radio: If set, the field is a set of radio buttons; if clear, the field is a check box. This flag is meaningful only if the Pushbutton flag is clear.',
          },
          coordinates: [98.4144, 313.006, 116.414, 331.006],
          field_instructions: 'Lawful Permenent Resident',
          struct_parent: 29,
          name: 'Permanent Resident',
          field_type: '/Btn',
          field_label: '',
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Citizenship/Permanent Resident',
        struct_parent: 29,
      },
      {
        type: '/Tx',
        var_name: 'Naturalization Date_af_date',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [432.306, 331.979, 489.426, 352.921],
          field_label: 'Naturalization Date_af_date',
          field_instructions: 'date naturalization granted',
          struct_parent: 28,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Naturalization Date_af_date',
        struct_parent: 28,
      },
      {
        type: '/Tx',
        var_name: 'Residency Date_af_date',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [414.305, 308.582, 471.425, 329.524],
          field_label: 'Residency Date_af_date',
          field_instructions: 'Date Residency Granted (mm/dd/yyyy)',
          struct_parent: 30,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Residency Date_af_date',
        struct_parent: 30,
      },
      {
        type: '/Tx',
        var_name: 'A-Number',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [296.28, 257.76, 507.96, 280.44],
          field_label: 'A-Number',
          field_instructions:
            'Alien Registration, Naturalization, or Citizenship Number',
          struct_parent: 31,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'A-Number',
        struct_parent: 31,
      },
      {
        type: '/Tx',
        var_name: 'Convict-Date_af_date',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [203.602, 218.822, 301.363, 245.342],
          field_label: 'Convict-Date_af_date',
          field_instructions: 'Convict Date',
          struct_parent: 32,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Convict-Date_af_date',
        struct_parent: 32,
      },
      {
        type: '/Tx',
        var_name: 'US District Court',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [451.2, 219, 522.72, 241.68],
          field_label: 'US District Court',
          field_instructions: 'US District Court',
          struct_parent: 33,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'US District Court',
        struct_parent: 33,
      },
      {
        type: '/Tx',
        var_name: 'Dist State',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [105.72, 187.92, 177.24, 210.6],
          field_label: 'Dist State',
          field_instructions: 'State',
          struct_parent: 34,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Dist State',
        struct_parent: 34,
      },
      {
        type: '/Btn',
        var_name: 'D.C. Superior Court 1',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Btn',
          coordinates: [196.873, 187.473, 214.873, 205.473],
          field_label: 'D.C. Superior Court 1',
          field_instructions: 'D.C. Superior Court',
          struct_parent: 35,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'D.C. Superior Court 1',
        struct_parent: 35,
      },
      {
        type: '/Tx',
        var_name: 'Docket No',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [114.016, 153.48, 262.576, 176.16],
          field_label: 'Docket No',
          field_instructions: 'Docket Number',
          struct_parent: 36,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Docket No',
        struct_parent: 36,
      },
      {
        type: '/Tx',
        var_name: 'Code Section',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [349.32, 153.48, 448.32, 176.16],
          field_label: 'Code Section',
          field_instructions: 'Code Section',
          struct_parent: 37,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Code Section',
        struct_parent: 37,
      },
      {
        type: '/Tx',
        var_name: 'Code Section_2',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [266.64, 121.44, 316.2, 144.12],
          field_label: 'Code Section_2',
          field_instructions: 'Code Section',
          struct_parent: 38,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Code Section_2',
        struct_parent: 38,
      },
      {
        type: '/Tx',
        var_name: 'US District Court_2',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [464.04, 121.32, 542.04, 144],
          field_label: 'US District Court_2',
          field_instructions: 'U.S. District Court',
          struct_parent: 39,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'US District Court_2',
        struct_parent: 39,
      },
      {
        type: '/Tx',
        var_name: 'District 2',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [105.72, 86.76, 188.16, 109.44],
          field_label: 'District 2',
          field_instructions: 'State',
          struct_parent: 40,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'District 2',
        struct_parent: 40,
      },
      {
        type: '/Btn',
        var_name: 'D.C. Superior Court 2',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Btn',
          coordinates: [205.967, 88.4836, 223.967, 106.484],
          field_label: 'D.C. Superior Court 2',
          field_instructions: 'D.C. Superior Court ',
          struct_parent: 41,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'D.C. Superior Court 2',
        struct_parent: 41,
      },
      {
        type: '/Tx',
        var_name: 'Docket No 2',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [403.92, 86.76, 525, 109.44],
          field_label: 'Docket No 2',
          field_instructions: 'Docket No 2',
          struct_parent: 42,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 2,
        path: 'Docket No 2',
        struct_parent: 42,
      },
      {
        type: '/Tx',
        var_name: 'App Date',
        field_dict: {
          font_info: '/Helvetica 12 Tf 0 g',
          flags: {},
          field_type: '/Tx',
          coordinates: [75.12, 396.72, 219.48, 425.52],
          field_label: 'App Date',
          field_instructions: 'Date',
          struct_parent: 44,
          hidden: false,
          child_fields: [],
          num_children: 0,
        },
        page_number: 3,
        path: 'App Date',
        struct_parent: 44,
      },
    ],
    grouped_items: [],
  },
  cache_id: 'Cache ID is not implemented yet',
};
