export const mockResponse = {
  message: 'PDF parsed successfully',
  parsed_pdf: {
    raw_text:
      "OMB Control No: 1123-0014 Expires 03/31/2027 \nAPPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF \nSIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF \nMARIJUANA \nOn October 6, 2022, President Biden issued a presidential proclamation that pardoned many federal and D.C. \noffenses for simple marijuana possession. On December 22, 2023, President Biden issued another proclamation that \nexpanded the relief provided by the original proclamation by pardoning the federal offenses of simple possession, \nattempted possession, and use of marijuana. \nHow a pardon can help you \nA pardon is an expression of the President’s forgiveness. It does not mean you are innocent or expunge your \nconviction. But it does remove civil disabilities—such as restrictions on the right to vote, to hold office, or to sit \non a jury—that are imposed because of the pardoned conviction. It may also be helpful in obtaining licenses, \nbonding, or employment. Learn more about the pardon. \nYou qualify for the pardon if: \n• On or before December 22, 2023, you were charged with or convicted of simple possession, attempted \npossession, or use of marijuana under the federal code, the District of Columbia code, or the Code of \nFederal Regulations \n• You were a U.S. citizen or lawfully present in the United States at the time of the offense \n• You were a U.S. citizen or lawful permanent resident on December 22, 2023 \nRequest a certificate to show proof of the pardon \nA Certificate of Pardon is proof that you were pardoned under the proclamation. The certificate is the only \ndocumentation you will receive of the pardon. Use the application below to start your request. \nWhat you'll need for the request \nAbout you \nYou can submit a request for yourself or someone else can submit on your behalf. You must provide \npersonal details, like name or citizenship status and either a mailing address, an email address or both to \ncontact you. We strongly recommend including an email address, if available, as we may not be able to \nrespond as quickly if you do not provide it. You can also use the mailing address or email address of \nanother person, if you do not have your own. \nAbout the charge or conviction \nYou must state whether it was a charge or conviction, the court district where it happened, and the date \n(month, day, year). If possible, you should also: \n• enter information about your case (docket or case number and the code section that was \ncharged) \n• upload your documents \no charging documents, like the indictment, complaint, criminal information, ticket or \ncitation; or \no conviction documents, like the judgment of conviction, the court docket sheet showing \nthe sentence and date it was imposed, or if you did not go to court, the receipt showing \npayment of fine \nIf you were charged by a ticket or citation and paid a fine instead of appearing in court, you should also provide the \ndate of conviction or the date the fine was paid. \nWithout this information, we can't guarantee that we'll be able to determine if you qualify for the pardon under \nthe proclamation. \n \nPage 1 of 4 \nUnited States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024 OMB Control No: 1123-0014 Expires 03/31/2027 \nAPPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF \nSIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF \nMARIJUANA \nInstructions: \nAn online version of this application is available at: Presidential Proclamation on Marijuana Possession \n(justice.gov). You can also complete and return this application with the required documents to \nUSPardon.Attorney@usdoj.gov or U.S. Department of Justice, Office of the Pardon Attorney, 950 Pennsylvania \nAvenue NW, Washington, DC 20530. \nPublic Burden Statement: \nThis collection meets the requirements of 44 U.S.C. § 3507, as amended by the Paperwork Reduction Act of 1995. \nWe estimate that it will take 120 minutes to read the instructions, gather the relevant materials, and answer \nquestions on the form. Send comments regarding the burden estimate or any other aspect of this collection of \ninformation, including suggestions for reducing this burden, to Office of the Pardon Attorney, U.S. Department of \nJustice, Attn: OMB Number 1123-0014, RFK Building, 950 Pennsylvania Avenue, N.W., Washington DC 20530. \nThe OMB Clearance number, 1123-0014, is currently valid. \nPrivacy Act Statement: \nThe Office of the Pardon Attorney has authority to collect this information under the U.S. Constitution, Article \nII, Section 2 (the pardon clause); Orders of the Attorney General Nos. 1798-93, 58 Fed. Reg. 53658 and 53659 \n(1993), 2317-2000, 65 Fed. Reg. 48381 (2000), and 2323-2000, 65 Fed. Reg. 58223 and 58224 (2000), codified in \n28 C.F.R. §§ 1.1 et seq. (the rules governing petitions for executive clemency); and Order of the Attorney General \nNo. 1012-83, 48 Fed. Reg. 22290 (1983), as codified in 28 C.F.R. §§ 0.35 and 0.36 (the authority of the Office of \nthe Pardon Attorney). The principal purpose for collecting this information is to enable the Office of the Pardon \nAttorney to issue an individual certificate of pardon to you. The routine uses which may be made of this \ninformation include provision of data to the President and his staff, other governmental entities, and the public. \nThe full list of routine uses for this correspondence can be found in the System of Records Notice titled, “Privacy \nAct of 1974; System of Records,” published in Federal Register, September 15, 2011, Vol. 76, No. 179, at pages \n57078 through 57080; as amended by “Privacy Act of 1974; System of Records,” published in the Federal \nRegister, May 25, 2017, Vol. 82, No. 100, at page 24161, and at the U.S. Department of Justice, Office of Privacy \nand Civil Liberties' website at: https://www.justice.gov/opcl/doj-systems-records#OPA. \nBy signing the attached form, you consent to allowing the Office of the Pardon Attorney to obtain information \nregarding your citizenship and/or immigration status from the courts, from other government agencies, from other \ncomponents within the Department of Justice, and from the Department of Homeland Security, U.S. Citizenship \nand Immigration Services (DHS-USCIS), Systematic Alien Verification for Entitlements (SAVE) program. The \ninformation received from these sources will be used for the sole purposes of determining an applicant's \nqualification for a Certificate of Pardon under the (cid:37)(cid:70)(cid:68)(cid:70)(cid:78)(cid:67)(cid:70)(cid:83)(cid:1)(cid:19)(cid:19) proclamation and for record-keeping of those \ndeterminations. Further, please be aware that if the Office of the Pardon Attorney is unable to verify your \ncitizenship or immigration status based on the information provided below, we may contact you to obtain \nadditional verification information. Learn more about the DHS-USCIS's SAVE program and its ordinary uses. \nYour disclosure of information to the Office of the Pardon Attorney on this form is voluntary. If you do not \ncomplete all or some of the information fields in this form, however, the Office of the Pardon Attorney may not be \nable to effectively respond. Information regarding gender, race, or ethnicity is not required and will not affect the \nprocessing of the application. \nNote: Submit a separate form for each conviction or charge for which you are seeking a certificate of pardon. \nApplication Form on page 3. \nPage 2 of 4 \nUnited States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024 OMB Control No: 1123-0014 Expires 03/31/2027 \nAPPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF \nSIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF \nMARIJUANA \nComplete the following: \nName: \n(first) (middle) (last) \nName at Conviction: \n(if different) (first) (middle) (last) \nAddress: \n(number) (street) (apartment/unit no.) \n\n(city) (state) (Zip Code) \nEmail Address:  Phone Number:  \nDate of Birth: Gender:  Are you Hispanic or Latino?: Yes No \nRace: Alaska Native or American Indian Asian Black or African American \nNative Hawaiian or Other Pacific Islander White Other \nCitizenship or Residency Status: \nU.S. citizen by birth \nU.S. naturalized citizen Date Naturalization Granted: \nLawful Permanent Resident Date Residency Granted: \nAlien Registration Number (A-Number), Certificate of Naturalization Number, or Citizenship Number \n(if applicant is a lawful permanent resident or naturalized citizen):  \n(A-Number) \n1.  Applicant was convicted on:  (month/day/year) in the U.S. District Court for the  (Northern, etc.) \nDistrict of  (state) or D.C. Superior Court of simple possession of marijuana, under \nDocket No. : (docket number) and Code Section:  ; (code section) OR \n2.  Applicant was charged with Code Section: (code section)  in the U.S. District Court for the  (Eastern, etc.) \nDistrict of  (state) or D.C. Superior Court under Docket No:  (docket number) \n \nUnited States Department of Justice Office of the Pardon Attorney Page 3 of 4 Washington, D.C. 20530 January 2024 OMB Control No: 1123-0014 Expires 03/31/2027 \nAPPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF \nSIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF \nMARIJUANA \nWith knowledge of the penalties for false statements to Federal Agencies, as provided by 18 \nU.S.C. § 1001, and with knowledge that this statement is submitted by me to affect action by \nthe U.S. Department of Justice, I certify that: \n1. The applicant was either a U.S. citizen or lawfully present in the United States at the time of the \noffense. \n2. The applicant was a U.S. citizen or lawful permanent resident on December 22, 2023. \n3. The above statements, and accompanying documents, are true and complete to the \n best of my knowledge, information, and belief. \n4. I acknowledge that any certificate issued in reliance on the above information will be \nvoided, if the information is subsequently determined to be false. \n\n(date) (signature) \nPage 4 of 4 \nUnited States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024 ",
    form_summary: {
      component_type: 'form_summary',
      title:
        'Application for Certificate of Pardon for Simple Possession, Attempted Possession, and Use of Marijuana',
      description:
        'On October 6, 2022, President Biden issued a presidential proclamation that pardoned many federal and D.C. offenses for simple marijuana possession. On December 22, 2023, President Biden issued another proclamation that expanded the relief provided by the original proclamation by pardoning the federal offenses of simple possession, attempted possession, and use of marijuana.',
    },
    elements: [
      {
        component_type: 'paragraph',
        text: "OMB Control No: 1123-0014 Expires 03/31/2027 APPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF SIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF MARIJUANA On October 6, 2022, President Biden issued a presidential proclamation that pardoned many federal and D.C. offenses for simple marijuana possession. On December 22, 2023, President Biden issued another proclamation that expanded the relief provided by the original proclamation by pardoning the federal offenses of simple possession, attempted possession, and use of marijuana. How a pardon can help you A pardon is an expression of the President’s forgiveness. It does not mean you are innocent or expunge your conviction. But it does remove civil disabilities—such as restrictions on the right to vote, to hold office, or to sit on a jury—that are imposed because of the pardoned conviction. It may also be helpful in obtaining licenses, bonding, or employment. Learn more about the pardon. You qualify for the pardon if: • On or before December 22, 2023, you were charged with or convicted of simple possession, attempted possession, or use of marijuana under the federal code, the District of Columbia code, or the Code of Federal Regulations • You were a U.S. citizen or lawfully present in the United States at the time of the offense • You were a U.S. citizen or lawful permanent resident on December 22, 2023 Request a certificate to show proof of the pardon A Certificate of Pardon is proof that you were pardoned under the proclamation. The certificate is the only documentation you will receive of the pardon. Use the application below to start your request. What you'll need for the request About you You can submit a request for yourself or someone else can submit on your behalf. You must provide personal details, like name or citizenship status and either a mailing address, an email address or both to contact you. We strongly recommend including an email address, if available, as we may not be able to respond as quickly if you do not provide it. You can also use the mailing address or email address of another person, if you do not have your own. About the charge or conviction You must state whether it was a charge or conviction, the court district where it happened, and the date (month, day, year). If possible, you should also: • enter information about your case (docket or case number and the code section that was charged) • upload your documents o charging documents, like the indictment, complaint, criminal information, ticket or citation; or o conviction documents, like the judgment of conviction, the court docket sheet showing the sentence and date it was imposed, or if you did not go to court, the receipt showing payment of fine If you were charged by a ticket or citation and paid a fine instead of appearing in court, you should also provide the date of conviction or the date the fine was paid. Without this information, we can't guarantee that we'll be able to determine if you qualify for the pardon under the proclamation. Page 1 of 4 United States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024",
        style: 'normal',
        page: 0,
      },
      {
        component_type: 'paragraph',
        text: "OMB Control No: 1123-0014 Expires 03/31/2027 APPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF SIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF MARIJUANA Instructions: An online version of this application is available at: Presidential Proclamation on Marijuana Possession (justice.gov). You can also complete and return this application with the required documents to USPardon.Attorney@usdoj.gov or U.S. Department of Justice, Office of the Pardon Attorney, 950 Pennsylvania Avenue NW, Washington, DC 20530. Public Burden Statement: This collection meets the requirements of 44 U.S.C. § 3507, as amended by the Paperwork Reduction Act of 1995. We estimate that it will take 120 minutes to read the instructions, gather the relevant materials, and answer questions on the form. Send comments regarding the burden estimate or any other aspect of this collection of information, including suggestions for reducing this burden, to Office of the Pardon Attorney, U.S. Department of Justice, Attn: OMB Number 1123-0014, RFK Building, 950 Pennsylvania Avenue, N.W., Washington DC 20530. The OMB Clearance number, 1123-0014, is currently valid. Privacy Act Statement: The Office of the Pardon Attorney has authority to collect this information under the U.S. Constitution, Article II, Section 2 (the pardon clause); Orders of the Attorney General Nos. 1798-93, 58 Fed. Reg. 53658 and 53659 (1993), 2317-2000, 65 Fed. Reg. 48381 (2000), and 2323-2000, 65 Fed. Reg. 58223 and 58224 (2000), codified in 28 C.F.R. §§ 1.1 et seq. (the rules governing petitions for executive clemency); and Order of the Attorney General No. 1012-83, 48 Fed. Reg. 22290 (1983), as codified in 28 C.F.R. §§ 0.35 and 0.36 (the authority of the Office of the Pardon Attorney). The principal purpose for collecting this information is to enable the Office of the Pardon Attorney to issue an individual certificate of pardon to you. The routine uses which may be made of this information include provision of data to the President and his staff, other governmental entities, and the public. The full list of routine uses for this correspondence can be found in the System of Records Notice titled, “Privacy Act of 1974; System of Records,” published in Federal Register, September 15, 2011, Vol. 76, No. 179, at pages 57078 through 57080; as amended by “Privacy Act of 1974; System of Records,” published in the Federal Register, May 25, 2017, Vol. 82, No. 100, at page 24161, and at the U.S. Department of Justice, Office of Privacy and Civil Liberties' website at: https://www.justice.gov/opcl/doj-systems-records#OPA. By signing the attached form, you consent to allowing the Office of the Pardon Attorney to obtain information regarding your citizenship and/or immigration status from the courts, from other government agencies, from other components within the Department of Justice, and from the Department of Homeland Security, U.S. Citizenship and Immigration Services (DHS-USCIS), Systematic Alien Verification for Entitlements (SAVE) program. The information received from these sources will be used for the sole purposes of determining an applicant's qualification for a Certificate of Pardon under the (cid:37)(cid:70)(cid:68)(cid:70)(cid:78)(cid:67)(cid:70)(cid:83)(cid:1)(cid:19)(cid:19) proclamation and for record-keeping of those determinations. Further, please be aware that if the Office of the Pardon Attorney is unable to verify your citizenship or immigration status based on the information provided below, we may contact you to obtain additional verification information. Learn more about the DHS-USCIS's SAVE program and its ordinary uses. Your disclosure of information to the Office of the Pardon Attorney on this form is voluntary. If you do not complete all or some of the information fields in this form, however, the Office of the Pardon Attorney may not be able to effectively respond. Information regarding gender, race, or ethnicity is not required and will not affect the processing of the application. Note: Submit a separate form for each conviction or charge for which you are seeking a certificate of pardon. Application Form on page 3. Page 2 of 4 United States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024",
        style: 'normal',
        page: 1,
      },
      {
        component_type: 'paragraph',
        text: 'OMB Control No: 1123-0014 Expires 03/31/2027 APPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF SIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF MARIJUANA Complete the following:',
        style: 'normal',
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Your Name: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Fst Name 1',
            label: 'First Name',
            default_value: '',
            required: true,
            page: 2,
          },
          {
            component_type: 'text_input',
            id: 'Mid Name 1',
            label: 'Middle Name',
            default_value: '',
            required: true,
            page: 2,
          },
          {
            component_type: 'text_input',
            id: 'Lst Name 1',
            label: 'Last Name',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Name at Conviction: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Conv Fst Name',
            label: 'First Name at Conviction',
            default_value: '',
            required: true,
            page: 2,
          },
          {
            component_type: 'text_input',
            id: 'Conv Mid Name',
            label: 'Middle Name at Conviction',
            default_value: '',
            required: true,
            page: 2,
          },
          {
            component_type: 'text_input',
            id: 'Conv Lst Name',
            label: 'Last Name at Conviction',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Your Address',
        fields: [
          {
            component_type: 'text_input',
            id: 'Address',
            label: 'Address (number, street, apartment/unit number)',
            default_value: '',
            required: true,
            page: 2,
          },
          {
            component_type: 'text_input',
            id: 'City',
            label: 'City',
            default_value: '',
            required: true,
            page: 2,
          },
          {
            component_type: 'text_input',
            id: 'State',
            label: 'State',
            default_value: '',
            required: true,
            page: 2,
          },
          {
            component_type: 'text_input',
            id: 'Zip Code',
            label: '(Zip Code)',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Email Address: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Email Address',
            label: 'Email Address',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Phone Number: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Phone Number',
            label: 'Phone Number',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Date of Birth',
        fields: [
          {
            component_type: 'text_input',
            id: 'Date of Birth',
            label: 'Date of Birth',
            default_value: '',
            required: true,
            page: 2,
          },
          {
            component_type: 'text_input',
            id: 'Gender',
            label: 'Gender',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'radio_group',
        legend: 'Are you Hispanic or Latino?: ',
        options: [
          {
            id: 'Yes',
            label: 'Yes ',
            name: 'Yes',
            default_checked: false,
            page: 2,
          },
          {
            id: 'No',
            label: 'No ',
            name: 'No',
            default_checked: false,
            page: 2,
          },
        ],
        id: 'Ethnicity',
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Race:',
        fields: [
          {
            component_type: 'checkbox',
            id: 'Nat Amer',
            label: 'Alaska Native or American Indian ',
            default_checked: false,
            struct_parent: 20,
            page: 2,
          },
          {
            component_type: 'checkbox',
            id: 'Asian',
            label: 'Asian ',
            default_checked: false,
            struct_parent: 21,
            page: 2,
          },
          {
            component_type: 'checkbox',
            id: 'Blck Amer',
            label: 'Black or African American ',
            default_checked: false,
            struct_parent: 22,
            page: 2,
          },
          {
            component_type: 'checkbox',
            id: 'Nat Haw Islander',
            label: 'Native Hawaiian or Other Pacific Islander ',
            default_checked: false,
            struct_parent: 23,
            page: 2,
          },
          {
            component_type: 'checkbox',
            id: 'White',
            label: 'White ',
            default_checked: false,
            struct_parent: 24,
            page: 2,
          },
          {
            component_type: 'checkbox',
            id: 'Other',
            label: 'Other ',
            default_checked: false,
            struct_parent: 25,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'radio_group',
        legend: 'Citizenship or Residency Status: ',
        options: [
          {
            id: 'Birth',
            label: 'U.S. citizen by birth ',
            name: 'Birth',
            default_checked: false,
            page: 2,
          },
          {
            id: 'Naturalized',
            label: 'U.S. naturalized citizen ',
            name: 'Naturalized',
            default_checked: false,
            page: 2,
          },
          {
            id: 'Permanent_Resident',
            label: 'Lawful Permanent Resident ',
            name: 'Permanent_Resident',
            default_checked: false,
            page: 2,
          },
        ],
        id: 'Citizenship',
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Date Naturalization Granted: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Naturalization Date_af_date',
            label: 'date naturalization granted',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Date Residency Granted: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Residency Date_af_date',
            label: 'Date Residency Granted (mm/dd/yyyy)',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend:
          'Alien Registration Number (A-Number), Certificate of Naturalization Number, or Citizenship Number',
        fields: [
          {
            component_type: 'text_input',
            id: 'A-Number',
            label: 'Alien Registration, Naturalization, or Citizenship Number',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: ' Applicant was convicted on: ',
        fields: [
          {
            component_type: 'text_input',
            id: 'Convict-Date_af_date',
            label: 'Convict Date',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend:
          'Which U.S. District Court or D.C. Superior Court heard or oversaw your case?',
        fields: [
          {
            component_type: 'text_input',
            id: 'US District Court',
            label: 'Court:',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend:
          'Enter the Code Section, the statute of your charge/conviction.',
        fields: [
          {
            component_type: 'text_input',
            id: 'Dist State',
            label: 'Code Section:',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'fieldset',
        legend: 'Enter the Docket Number assigned to your case by the court.',
        fields: [
          {
            component_type: 'text_input',
            id: 'Docket No',
            label: 'Docket Number:',
            default_value: '',
            required: true,
            page: 2,
          },
        ],
        page: 2,
      },
      {
        component_type: 'paragraph',
        text: 'OMB Control No: 1123-0014 Expires 03/31/2027 APPLICATION FOR CERTIFICATE OF PARDON FOR THE OFFENSES OF SIMPLE POSSESSION, ATTEMPTED SIMPLE POSSESSION, OR USE OF MARIJUANA With knowledge of the penalties for false statements to Federal Agencies, as provided by 18 U.S.C. § 1001, and with knowledge that this statement is submitted by me to affect action by the U.S. Department of Justice, I certify that: 1. The applicant was either a U.S. citizen or lawfully present in the United States at the time of the offense. 2. The applicant was a U.S. citizen or lawful permanent resident on December 22, 2023. 3. The above statements, and accompanying documents, are true and complete to the best of my knowledge, information, and belief. 4. I acknowledge that any certificate issued in reliance on the above information will be voided, if the information is subsequently determined to be false.',
        style: 'normal',
        page: 3,
      },
      {
        component_type: 'fieldset',
        legend: 'App Date',
        fields: [
          {
            component_type: 'text_input',
            id: 'App Date',
            label: 'Date',
            default_value: '',
            required: true,
            page: 3,
          },
        ],
        page: 3,
      },
      {
        component_type: 'paragraph',
        text: '(date) (signature) Page 4 of 4 United States Department of Justice Office of the Pardon Attorney Washington, D.C. 20530 January 2024',
        style: 'normal',
        page: 3,
      },
    ],
    raw_fields: [],
    grouped_items: [],
  },
  cache_id: '773d494445e84392eae438064a3d7c5e5d1829d0b46bff120cf050fdeebd6f1c',
};
