name: Apply Terraform CDK configuration

on:
  workflow_call:

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Terraform CDK configuration
        shell: bash
        run: |
          cd infra
          pnpm cdktf get
          pnpm build:tsc

      - name: Install CloudFoundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | sudo tar -zx --directory=/usr/local/bin
          cf --version

      - name: Apply Terraform CDK configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash
        run: |
          cd infra
          cf api https://api.fr.cloud.gov
          DEPLOY_ENV=${TAG_NAME} pnpm cdktf deploy --auto-approve
