name: Validate

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Lint source code
        shell: bash
        run: pnpm lint

      - name: Run test suite
        shell: bash
        run: pnpm test

      - name: Initialize Terraform CDK configuration
        shell: bash
        run: |
          cd infra
          pnpm cdktf get
          pnpm build:tsc

      - name: Typecheck source code
        shell: bash
        run: pnpm typecheck

      #- name: Vitest Coverage Report
      #  if: always()
      #  uses: davelosert/vitest-coverage-report-action@v2.2.0
