# Relevant base images:
#   docassemble-os: https://github.com/jhpyle/docassemble-os/blob/master/Dockerfile
#   docassemble: https://github.com/jhpyle/docassemble/blob/master/Dockerfile
FROM jhpyle/docassemble:latest

#ADD ./startup.sh /usr/local/bin/startup.sh
#CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
