version: '3'

services:
  web:
    image: jhpyle/docassemble:latest
    ports:
      - '8011:80'
    # The available environment variables have defaults defined in the base image:
    #   https://github.com/jhpyle/docassemble/blob/master/Dockerfile
    # Configuration documentation is available here:
    #   https://docassemble.org/docs/docker.html#configuration%20options
    environment:
      CONTAINERROLE: 'all'
