version: '3'

services:
  web:
    image: jhpyle/docassemble
    ports:
      - '8011:80'
    volumes:
      - data:/usr/share/docassemble/data
      - log:/usr/share/docassemble/log
      - config:/usr/share/docassemble/config
      - webapp:/usr/share/docassemble/webapp
  redis:
    image: 'redis:latest'
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: docassemble
      POSTGRES_USER: docassemble
      POSTGRES_PASSWORD: secret-password
volumes:
  data:
  log:
  config:
  webapp:
