import * as z from 'zod';

export const stateTerritoryOrMilitaryPostList = [
  { abbr: 'AL', label: 'AL - Alabama' },
  { abbr: 'AK', label: 'AK - Alaska' },
  { abbr: 'AS', label: 'AS - American' },
  { abbr: 'AZ', label: 'AZ - Arizona' },
  { abbr: 'AR', label: 'AR - Arkansas' },
  { abbr: 'CA', label: 'CA - California' },
  { abbr: 'CO', label: 'CO - Colorado' },
  { abbr: 'CT', label: 'CT - Connecticut' },
  { abbr: 'DE', label: 'DE - Delaware' },
  { abbr: 'DC', label: 'DC - District' },
  { abbr: 'FL', label: 'FL - Florida' },
  { abbr: 'GA', label: 'GA - Georgia' },
  { abbr: 'GU', label: 'GU - Guam' },
  { abbr: 'HI', label: 'HI - Hawaii' },
  { abbr: 'ID', label: 'ID - Idaho' },
  { abbr: 'IL', label: 'IL - Illinois' },
  { abbr: 'IN', label: 'IN - Indiana' },
  { abbr: 'IA', label: 'IA - Iowa' },
  { abbr: 'KS', label: 'KS - Kansas' },
  { abbr: 'KY', label: 'KY - Kentucky' },
  { abbr: 'LA', label: 'LA - Louisiana' },
  { abbr: 'ME', label: 'ME - Maine' },
  { abbr: 'MD', label: 'MD - Maryland' },
  { abbr: 'MA', label: 'MA - Massachusetts' },
  { abbr: 'MI', label: 'MI - Michigan' },
  { abbr: 'MN', label: 'MN - Minnesota' },
  { abbr: 'MS', label: 'MS - Mississippi' },
  { abbr: 'MO', label: 'MO - Missouri' },
  { abbr: 'MT', label: 'MT - Montana' },
  { abbr: 'NE', label: 'NE - Nebraska' },
  { abbr: 'NV', label: 'NV - Nevada' },
  { abbr: 'NH', label: 'NH - New' },
  { abbr: 'NJ', label: 'NJ - New' },
  { abbr: 'NM', label: 'NM - New' },
  { abbr: 'NY', label: 'NY - New' },
  { abbr: 'NC', label: 'NC - North' },
  { abbr: 'ND', label: 'ND - North' },
  { abbr: 'MP', label: 'MP - Northern' },
  { abbr: 'OH', label: 'OH - Ohio' },
  { abbr: 'OK', label: 'OK - Oklahoma' },
  { abbr: 'OR', label: 'OR - Oregon' },
  { abbr: 'PA', label: 'PA - Pennsylvania' },
  { abbr: 'PR', label: 'PR - Puerto' },
  { abbr: 'RI', label: 'RI - Rhode' },
  { abbr: 'SC', label: 'SC - South' },
  { abbr: 'SD', label: 'SD - South' },
  { abbr: 'TN', label: 'TN - Tennessee' },
  { abbr: 'TX', label: 'TX - Texas' },
  { abbr: 'UM', label: 'UM - United' },
  { abbr: 'UT', label: 'UT - Utah' },
  { abbr: 'VT', label: 'VT - Vermont' },
  { abbr: 'VI', label: 'VI - Virgin' },
  { abbr: 'VA', label: 'VA - Virginia' },
  { abbr: 'WA', label: 'WA - Washington' },
  { abbr: 'WV', label: 'WV - West' },
  { abbr: 'WI', label: 'WI - Wisconsin' },
  { abbr: 'WY', label: 'WY - Wyoming' },
  { abbr: 'AA', label: 'AA - Armed Forces Americas' },
  { abbr: 'AE', label: 'AE - Armed Forces Africa' },
  { abbr: 'AE', label: 'AE - Armed Forces Canada' },
  { abbr: 'AE', label: 'AE - Armed Forces Europe' },
  { abbr: 'AE', label: 'AE - Armed Forces Middle East' },
  { abbr: 'AP', label: 'AP - Armed Forces Pacific' },
] as const;

export const stateTerritoryOrMilitaryPostAbbreviations = z.union([
  z.literal('AL'),
  z.literal('AK'),
  z.literal('AS'),
  z.literal('AZ'),
  z.literal('AR'),
  z.literal('CA'),
  z.literal('CO'),
  z.literal('CT'),
  z.literal('DE'),
  z.literal('DC'),
  z.literal('FL'),
  z.literal('GA'),
  z.literal('GU'),
  z.literal('HI'),
  z.literal('ID'),
  z.literal('IL'),
  z.literal('IN'),
  z.literal('IA'),
  z.literal('KS'),
  z.literal('KY'),
  z.literal('LA'),
  z.literal('ME'),
  z.literal('MD'),
  z.literal('MA'),
  z.literal('MI'),
  z.literal('MN'),
  z.literal('MS'),
  z.literal('MO'),
  z.literal('MT'),
  z.literal('NE'),
  z.literal('NV'),
  z.literal('NH'),
  z.literal('NJ'),
  z.literal('NM'),
  z.literal('NY'),
  z.literal('NC'),
  z.literal('ND'),
  z.literal('MP'),
  z.literal('OH'),
  z.literal('OK'),
  z.literal('OR'),
  z.literal('PA'),
  z.literal('PR'),
  z.literal('RI'),
  z.literal('SC'),
  z.literal('SD'),
  z.literal('TN'),
  z.literal('TX'),
  z.literal('UM'),
  z.literal('UT'),
  z.literal('VT'),
  z.literal('VI'),
  z.literal('VA'),
  z.literal('WA'),
  z.literal('WV'),
  z.literal('WI'),
  z.literal('WY'),
  z.literal('AA'),
  z.literal('AE'),
  z.literal('AE'),
  z.literal('AE'),
  z.literal('AE'),
  z.literal('AP'),
]);

type JurisdictionAbbr =
  (typeof stateTerritoryOrMilitaryPostList)[number]['abbr'];

export const getJurisdictionAbbreviations = (): JurisdictionAbbr[] =>
  stateTerritoryOrMilitaryPostList.map(j => j.abbr);
