name: "Performance checks"

on:
  workflow_call:

permissions:
  pull-requests: write

jobs:
  size:
    runs-on: ubuntu-latest

    steps:
      - name: Install and Build
        uses: ./.github/workflows/_node-install-and-build.yml

      - uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
          skip_step: build
          directory: ./apps/spotlight

      - uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
          skip_step: build
          directory: ./packages/design