name: Playwright Tests
on:
  workflow_call:
jobs:
  end_to_end:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm --filter=end-to-end-tests exec playwright install --with-deps
    - name: Debugging steps
      run: |
          echo "Workflow triggered in branch '${{ github.ref }}'."
          echo "Workflow triggered in head_ref '${{ github.head_ref }}'."
          echo "Workflow triggered by event '${{ github.event_name }}'."
          echo "Workflow triggered by actor '${{ github.actor }}''."
    - name: Determine E2E_ENDPOINT
      run: >
        echo E2E_ENDPOINT=$(if [[ "${{ github.event_name }}" == "pull_request" ]]; then
        echo "${{ vars.PREVIEW_URL }}/${{ github.head_ref }}";
        else
        echo "${{ vars.MAIN_URL }}";
        fi) >> $GITHUB_ENV
    - name: Run Playwright tests
      run: pnpm --filter=end-to-end-tests exec playwright test
      env:
        E2E_ENDPOINT: ${{ env.E2E_ENDPOINT }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30