name: Playwright Tests
on:
  workflow_call:
    inputs:
      head:
        type: string
        default: ${{ github.ref_name }}
      base:
        required: true
        type: string
jobs:
  end_to_end:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm --filter=end-to-end-tests exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm --filter=end-to-end-tests exec playwright test
      env:
        E2E_ENDPOINT: ${{ secrets.PULL_REQUEST_PREVIEW_URL }}/${{ github.head_ref }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
