name: Validate

on:
  workflow_call:
    inputs:
      playwright_version:
        description: Installed playwright version
        required: false
        default: "1.48.1"
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        shell: bash
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Install required node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ inputs.playwright_version }}

      - name: Install Playwright
        run: pnpm dlx playwright@${{ inputs.playwright_version }} install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      # While most of the test suite is self-contained, the tests for the demo
      # servers require a prod build of @atj/server.
      - name: Build
        run: pnpm build

      - name: Make directory for build artifacts
        run: mkdir -p output/build-artifacts


      - name: Spotlight app performance budget
        run: pnpm --filter @atj/spotlight size:ci > output/build-artifacts/spotlight-size-output.txt

      - name: Design package performance budget
        run: pnpm --filter @atj/design size:ci > output/build-artifacts/design-size-output.txt

      - name: Upload size:ci results
        uses: actions/upload-artifact@v4
        with:
          name: size-limit-results
          path: |
            output/build-artifacts/spotlight-size-output.txt
            output/build-artifacts/design-size-output.txt

      - name: Lint source code
        shell: bash
        run: pnpm lint

      - name: Run test suite
        shell: bash
        run: AUTH_SECRET=not-super-secret pnpm test:ci

      - name: Initialize Terraform CDK configuration
        shell: bash
        run: |
          cd infra/cdktf
          pnpm cdktf get
          pnpm build:tsc

      - name: Typecheck source code
        shell: bash
        run: pnpm typecheck

      # - name: Vitest Coverage Report
      #   if: always()
      #   uses: davelosert/vitest-coverage-report-action@v2.5.0
