name: Post Terraform plan to PR comment

on:
  pull_request:
    branches:
      - staging
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  add-terraform-plan-to-staging-pr:
    uses: ./.github/workflows/_terraform-plan-pr-comment.yml
    secrets: inherit
    with:
      deploy-env: ${{ github.base_ref }}
