name: Create PR from main to staging

on:
  push:
    branches:
      - main

jobs:
  create-pr-to-staging:
    uses: ./.github/workflows/_pr-create.yml
    secrets: inherit
    with:
      base: staging
