name: 'Run tests'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TAG_NAME: ${{ github.ref_name }}
  REGISTRY: ghcr.io/gsa-tts/atj-platform

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build . --platform linux/amd64 --target doj-demo --tag ${REGISTRY}/doj-demo:${TAG_NAME}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to container registry
        run: docker push ${REGISTRY}/doj-demo:${TAG_NAME}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        shell: bash
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Install required node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Initialize Terraform CDK configuration
        shell: bash
        run: |
          cd infra
          pnpm cdktf get
          pnpm build:tsc

      - name: Apply Terraform CDK configuration
        run: pnpm cdktf deploy --auto-approve
