name: 'Deploy'

on:
  push:
    branches:
      - main
      - staging
      - login-gov
  workflow_dispatch:

jobs:
  build-image-doj:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: server-doj
      #tag-name: ${{ github.ref_name }}
      tag-name: staging

  build-image-kansas:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: server-kansas
      #tag-name: ${{ github.ref_name }}
      tag-name: staging

  deploy:
    needs: [build-image-doj, build-image-kansas]
    uses: ./.github/workflows/_terraform-apply.yml
    secrets: inherit
    with:
      #deploy-env: ${{ github.ref_name }}
      deploy-env: staging
