name: 'Deploy'

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-image-doj:
    uses: ./.github/workflows/_build-docker-image.yml
    secrets: inherit
    with:
      app-name: doj-demo

  build-image-spotlight:
    uses: ./.github/workflows/_build-docker-image.yml
    secrets: inherit
    with:
      app-name: spotlight

  deploy:
    needs: [build-image-doj, build-image-spotlight]
    uses: ./.github/workflows/_apply-terraform.yml
    secrets: inherit
    with:
      deploy-env: ${{ github.ref_name }}
