name: 'Deploy'

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  build-image-doj:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: server-doj
      #tag-name: main

  build-image-kansas:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: server-kansas
      #tag-name: main

  deploy:
    needs: [build-image-doj, build-image-kansas]
    uses: ./.github/workflows/_terraform-apply.yml
    secrets: inherit
    #with:
    #  deploy-env: main
