name: 'Deploy'

on:
  push:
    branches:
      - main
    tags:
      - staging
  workflow_dispatch:

env:
  TAG_NAME: ${{ github.ref_name }}
  REGISTRY: ghcr.io/gsa-tts/atj-platform

jobs:
  build-image-doj:
    uses: ./.github/workflows/shared/build-docker-image.yml
    secrets: inherit
    with:
      app-name: doj-demo

  build-image-spotlight:
    uses: ./.github/workflows/shared/build-docker-image.yml
    secrets: inherit
    with:
      app-name: spotlight

  setup:
    uses: ./.github/workflows/shared/setup.yml

  deploy:
    uses: ./.github/workflows/shared/apply-terraform.yml
    secrets: inherit
