name: 'Deploy'

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  build-image-doj:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: doj-demo

  build-image-spotlight:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: spotlight

  deploy:
    needs: [build-image-doj, build-image-spotlight]
    uses: ./.github/workflows/_terraform-apply.yml
    secrets: inherit
    with:
      deploy-env: ${{ github.ref_name }}

  e2e:
    needs: [deploy]
    uses: ./.github/workflows/_playwright.yml
    secrets: inherit
