name: 'Deploy'

on:
  push:
    branches:
      - main
      - staging
      - astro-library
  workflow_dispatch:

env:
  DEPLOY_ENV: main
  #DEPLOY_ENV: ${{ github.ref_name }}

jobs:
  build-image-doj:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: server-doj
      tag-name: ${{ env.DEPLOY_ENV }}

  build-image-kansas:
    uses: ./.github/workflows/_docker-build-image.yml
    secrets: inherit
    with:
      app-name: server-kansas
      tag-name: ${{ env.DEPLOY_ENV }}

  deploy:
    needs: [build-image-doj, build-image-kansas]
    uses: ./.github/workflows/_terraform-apply.yml
    secrets: inherit
    with:
      deploy-env: ${{ env.DEPLOY_ENV }}
