name: 'Run tests'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    uses: ./.github/workflows/_validate.yml
  e2e:
    uses: ./.github/workflows/_end-to-end.yml
    secrets: inherit