name: 'Run tests'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/shared/setup.yml

  run-tests:
    uses: ./.github/workflows/shared/validate.yml
